### ISSUE TITLE
the following errors occurred in the installation

### ISSUE THREAD

**Issue by yoyomule** [AirenSoft/OvenMediaEngine#10]
Hello, the following errors occurred in the installation, please advise.
####################################################
#                                                  #
#           AirenSoft Make System v0.62            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 2
   - GCC version             : 7.3.0
   - Build option            : DEBUG
   - Total Projects count    : 24

[  1/151|  0%] Preparing directories...
[  2/151|  1%] [static] libovlibrary.a: C++ projects/base/ovlibrary/error.cpp => intermediates/DEBUG/objs/base/ovlibrary/error.o
**projects/base/ovlibrary/error.cpp:10:10: fatal error: srt/srt.h: No such file or directory
 #include <srt/srt.h>
          ^~~~~~~~~~~
compilation terminated.
core/build_objects.mk:18: recipe for target 'intermediates/DEBUG/objs/base/ovlibrary/error.o' failed
make: *** [intermediates/DEBUG/objs/base/ovlibrary/error.o] Error 1**

**Comment by sfreet** [comment]
Thank you for reporting this error.
We updated source code on December 18th.
A library dependency has been added, but the README file has not yet been updated.
We will update the README file within a few days.
To solve the problem you mentioned
First, Go to https://github.com/Haivision/srt and install the srt library. (you should run make install after make)

**Comment by yoyomule** [comment]
Thank you. But it still seems to be a problem.
![qq 20181220115613](https://user-images.githubusercontent.com/10000818/50262900-4d28f200-044e-11e9-8d26-d3f4568c0394.png)
![qq 20181220115608](https://user-images.githubusercontent.com/10000818/50262901-4d28f200-044e-11e9-842c-37b41524785c.png)

**Comment by yoyomule** [comment]
![image](https://user-images.githubusercontent.com/10000818/50533264-3fb3ec00-0b61-11e9-9a89-cc4d853d38fb.png)
![image](https://user-images.githubusercontent.com/10000818/50533267-48a4bd80-0b61-11e9-92d9-c525da1ca339.png)
![image](https://user-images.githubusercontent.com/10000818/50533273-52c6bc00-0b61-11e9-97a8-43e73ef3dc17.png)
Hello, after solving the above problems, there are still some problems in the deployment process. Look forward to more detailed documentation.

**Comment by dimiden** [comment]
After checking the attached logs, I see two problems. I hope you can solve the problem with the following information.

1. [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security) setup issue

Signalling between the browser and OME is done via WebSocket, so if you want to play a stream on an HTTPS page like [OvenPlayer Demo](https://airensoft.github.io/OvenPlayer/docs/index.html), you must use an encrypted WebSocket called WSS.
If you are testing on an HTTP page rather than HTTPS, skip to step 2.

To configure TLS, you must have a domain owned by you and a TLS certificate associated with that domain. TLS certificate can be issued from various [Certificate Authorities](https://en.wikipedia.org/wiki/Certificate_authority). Here, I will assume that you have already been issued.
The issued certificate file can be divided into cert file and private key file. You can add these files to ```<WebRTC>```-```<Signalling>```-```<TLS>``` element in ```Server.xml```.

```xml
<WebRTC>
        ...
	<Signalling>
		<TLS>
			<!-- certification file path for TLS servers -->
			<CertPath>/path/to/crt_file/cert_file_name.crt</CertPath>
			<!-- private key file path for TLS servers -->
			<KeyPath>/path/to/key_file/private_key_file_name.key</KeyPath>
		</TLS>
		<Port>3333</Port>
	</Signalling>
</WebRTC>
```

As the SRT and TLS functions have recently been released, the related content has not yet been applied to the README, and I'm really sorry to hear about this inconvenience.

2. The 1935 port is already in use

It seems that your server is already using the 1935 port. The 1935 port is very important because it is the port used to receive the RTMP input from Encoder such as [OBS](https://obsproject.com/). If you still get a "Could not bind to [v4] 0.0.0.0:1935" error, you can terminate the process using the 1935 port or change the RTMP port by referring to the following.

```xml
<Providers>
	<RTMP>
		<MaxConnection>10</MaxConnection>
		<!-- Please change this port number to another number. And do not forget to set it on OBS. -->
		<Port>1935</Port>
	</RTMP>
</Providers>
```

**Comment by yoyomule** [comment]
Thank you, the port problem has been solved, but it seems to be a problem.
![image](https://user-images.githubusercontent.com/10000818/50681461-882e4680-1046-11e9-90bf-9df31a850040.png)
![image](https://user-images.githubusercontent.com/10000818/50681468-90868180-1046-11e9-91be-21d2253ea67f.png)
![image](https://user-images.githubusercontent.com/10000818/50681485-a1cf8e00-1046-11e9-92d7-fc312ca07d43.png)

**Comment by dimiden** [comment]
1. Make sure that you are streaming to OME using a broadcast tool such as OBS.
2. In the OBS ```Settings``` - ```Stream``` tab, make sure that the ```Stream Type``` is set to ```Custom Streaming Server``` and the URL is ```rtmp://148.70.104.177/live``` and the stream key is ```123``` (```_o``` is a suffix that is required only when playing in a web browser).
3. ```IP``` in ```Publishers``` is used to send ICE candidate information. If you enter ```127.0.0.1```, your browser will try to connect to ```127.0.0.1```. So if OME and web browser are running on different machines, you have to enter the actual server IP. (According to the attached screenshot, set it to ```148.70.104.177```)
