### ISSUE TITLE
admission webhook virtualhost name

### ISSUE THREAD

**Issue by hatsch** [AirenSoft/OvenMediaEngine#1047]
Hi there,
i am currently replacing nginx-rtmp with ovenmediaengine for our community tv station.
one of our requirements is that we record all incoming streams. sometimes for legal reasons, sometimes as a service for our community members.
while ovenmedia engine allows recording streams, there is no way to automatically record all streams, or a given pattern of app/stream names.
i wrote a small helper api[1], that can be used as an admission webhook endpoint. there is a config.yml that specifies app/stream name patterns and sends to the startRecord API on opening and stopRecord on closing incoming requests.
it also features re submitting the POST request to another webhook ( if needed for eg. authorization )

one thing i noticed is that the Admission Webhook does not include the VirtualHost name. Therefore i default to default at the moment ( in fact the only one we are using atm)

for this and possibly other use cases it would be helpful to include the virtualhost's name in the admission webhook

anyway thank you for this awesome project.. i'm looking forward to deploy it to production :)

[1] https://github.com/dorftv/omcompanion/

**Comment by getroot** [comment]
As you know, Virtual Host is divided into Domain Name. So if you look at the HOST of the URL sent by Admissionwebhooks, you can find out which Virtual Hosts you have. Virtual Host Name is not difficult to map it because you have set it.

Note 1. The DUMP feature of LLHLS allows you to automatically record all streams.
https://airensoft.gitbook.io/ovenmediaengine/streaming/low- latency-hls#dump

Note 2. The existing recording function is also developed to be automatically dump like LLHLS DUMP.

**Comment by hatsch** [comment]
thank you for the hint with domain name. of course that's already available. i just missed that!

as for Note 1. this leads to lot's of segmented files, not suitable for eg postproduction.
but seems like Note 2. will resolve my issue finally.
