### ISSUE TITLE
LLHLS Publisher - Playback fails if there are multiple client sessions

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1303]
**Describe the bug**
When viewing more than one stream at a time from an LLHLS publisher, playback of both streams starts to fail.

**To Reproduce**
Open one LLHLS stream, then a second one in a new browser window. 'Invalid session_key' will begin to appear in the logs and playback will either hit errors or fail completely. Once you stop the second stream, playback of the first stream will resume normally and the 'Invalid session_key' errors disappear.

**Expected behavior**
Playback of one LLHLS stream should not impact playback of a different stream from the same client.

**Logs**
[log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/12031385/log.txt)

**Server (please complete the following information):**
Docker dev image, latest commits

**Player (please complete the following information):**
Chrome and Safari on macOS

**Additional context**
In my testing reflected in the log file, you can see alternating playback of one stream and the other, with no issue. Then when both streams are opened you will see the 'Invalid session_key' errors start streaming in.

**Comment by getroot** [comment]
Hmm... I can't reproduce this. Playing with multiple streams and multiple sessions works just fine.

The only way I can reproduce this even close is:

1. Enable AdmissionWebhooks or SignedPolicy, OriginMode is false
2. Create stream, play LLHLS
3. Deleting the stream without UNLOADing the player in (2) (the player is still retrying)
4. Create stream again
5. Invalid session key message output

The reason for the above reproduction is that the player did not load from the master playlist. AdmissionWebhooks or SignedPolicy checks only the master playlist for efficiency, not subsequent chunklis or segments. If the master playlist authentication passes, a session key is issued, which authorizes subsequent segment downloads.

In OvenPlayer or other players, if you do not UNLOAD PLAYER, the master playlist is first downloaded only once. Since the previously issued session key has already been deleted when the stream is deleted, it is not valid for the newly created stream. When the stream is recreated, the session key previously issued to the player has already expired, so this is a normal case for security reasons.

If you run UNLOAD PLAYER --> LOAD PLAYER again in Oven Player, then the master playlist will be downloaded again and authentication will pass.

Please let me know if the issue reproduces after UNLOAD PLAYER -> LOAD PLAYER. If your problem is not the case above, please write a little more detail on how to reproduce it. The browser you use or the timing of stream creation (your logs don't have any logs about stream creation, did you delete them on purpose?) may also be important. Server.xml is also required.

**Comment by bchah** [comment]
Thank you @getroot - I have tested this again with the latest commits and cannot reproduce it anymore. I had hit that error after a long day of testing so there could be some other factors I didn't realize, sorry for the poor reporting.

One thing regarding logs... for logger.xml this is the configuration I am using so I don't know why the stream creation logs you are looking for aren't being included:

```
<Logger version="2">
	<Path>/log/engine</Path>
	<!-- HttpServer is overly verbose so should always be supressed -->
	<Tag name="HttpServer" level="critical"/>
	<Tag name=".*" level="info" />
</Logger>
```

**Comment by manish-drake** [comment]
Hey @getroot , could you please look at the discussion topic https://github.com/AirenSoft/OvenMediaEngine/discussions/1822
I am facing a similar issue but with nginx reverse proxy.
