### ISSUE TITLE
Queue size exceeded message on v0.10.3

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#134]
Hi All!

Since I moved from v0.10.2 to v0.10.3 I started to receive these warnings:

**[2020-06-18 11:43:58.834] W 28950 ov.Queue | queue.h:179  | [0x7f23e7f2cbd8] WebRTC Publisher Application/#default#app2/stream2 StreamWorker Queue size has exceeded the threshold: queue: 100, threshold: 100**

May I have a hint about what is wrong?

Many thanks to you all!

**Comment by swedishdeveloper** [comment]
Hello!
I have exactly same problem on OME v0.10.3. Something seems to be wrong. I have also noticed that the Audio encoding from AAC to OPUS seems also be a quite slow. Does OME Support OPUS input directly? Btw I hope they fix these issues as fast as possible.

**Comment by getroot** [comment]
If the queue size no longer increases from 100, that is not a problem. We output the logs to all internal queues at 0.10.3 to measure the performance of the OME, and it seems that the logs are suddenly caused by it. (It's also a problem in StreamWorker that we set the threshold too small. We will increase this.)

If the queue size of StreamWorker continues to increase, try increasing the number of threads in the following settings.

<Publishers>
<ThreadCount>4</ThreadCount>
</Publishers>

OPUS encoding performance is not something we can control. We are using the open OPUS Codec. But we'll see if there are other options for Opus codec.

It is possible to support opus input. But there is no encoder that supports it. RTMP also does not support it. (How can you input OPUS audio?) RTMP only supports H.264 and AAC.

**Comment by nangavar** [comment]
Thank you getroot!  Will try changing ThreadCount.

**Comment by nangavar** [comment]
I found that when I start getting this error the stream starts to get some lagging issues.
