### ISSUE TITLE
How to use RTSP Input?

### ISSUE THREAD

**Issue by swedishdeveloper** [AirenSoft/OvenMediaEngine#135]
Hello!

As I understand you are supporting RTSP Input in experimental mode? But how to I configure it.
Which port is used for RTSP and do you use TCP or UDP protocol for that? Or something else?

I am using FFMPEG to push the stream to the server. For RTMP inputs it's working fine from FFMPEG, but I want to test out your RTSP solution to get better latency, so I have changed the broadcast URL to like this
rtsp://mydomain:1935/app/test is that correct or do you use the 554 port?

I have checked the configuration guide at: https://airensoft.gitbook.io/ovenmediaengine/ without results. So Please can you tell me how to setup it up.

@getroot @dimiden 

Kind Regards
Benjamin

**Comment by nangavar** [comment]
Hi Swedishdeveloper!

Im using RTSP-pulling without any problem.

First declare your RTSP port:
```xml
<Bind>
	<Providers>
		<RTSP>
			<Port>554</Port>
		</RTSP>
	</Providers>
</Bind>
```
Then you should declare your RTSP source as an origin. OME will look the requested "stream key" and "app" into locations, and when it matches it will try to connect to the pass URL where it is supposed that the RTSP is available..
```xml
<Origins>
	<Origin>
		<Location>/app/stream_key</Location>
		<Pass>
			<Scheme>rtsp</Scheme>
			<Urls><Url>RTSP_SOURCE_IP:554/...</Url></Urls>
		</Pass>
	</Origin>
</Origins>
```
Finally you should enable RTSPPull as a provider into the application.
```xml
<Applications>
	<Application>
		<Providers>
			<!-- <RTMP /> -->
			<RTSPPull />
			</Providers>
	</Application>
<Applications>
```
Hope this helps

**Comment by getroot** [comment]
@nangavar 
Thank you very much for explaining on your behalf. We haven't opened that information yet, how do you know that? You are amazing.

However, we will correct some information.

The information below is only needed for RTSP Push (OME becomes an RTSP server) to be developed in the future.
```
<Bind>
<Providers>
<RTSP>
<Port>554</Port>
</RTSP>
</Providers>
</Bind>
```

**Comment by getroot** [comment]
@swedishdeveloper 
Right now, as nangavar mentioned, only RTSP Pull is supported. RTSP Push is not yet supported.

**Comment by nangavar** [comment]
@getroot
hahaha too many hours with OME lately...
Thanks! I will delete that port from my config.

**Comment by swedishdeveloper** [comment]
Good morning, from Sweden!

Thank you for your answers. I have to wait until you enter some code for RTSP-Push because that's really what I'm waiting for because I'm already reading the stream with WebRTC and it works fine.

I noticed that you have written "MPEG-TS / UDP Push Input" as experimental. But now I will come to the same point again, how should I configure OME to test "MPEG-TS / UDP Push Input"? Which port should I use etc.? You should perhaps create a guide for the DEV version of OME in the guidebook as well. It would be great for those who want to test your beta versions of the Program. That would be appreciated.

Then also, do you have any ideas on how to do get down latency. I use FFMPEG and have set bframes to 0, profile to baseline, using bypass in ome, the tune is set to zerolatency and image format to flv for the only thing that RTMP supports at present. But I still have a latency of 1-2 seconds, would like to get it down to around 500 ms at least. I think the only solution is RTSP or MPEG-TS but I don't know. You seem to know a lot more about live streaming services than I anyway, really good you are.

Thanks for your quick answers.

Sincerely
Benjamin

**Comment by getroot** [comment]
@swedishdeveloper 
RTMP Push is not currently available for some reasons. This is put on hold for a while due to the high priority task. Only RTSP Pull is available at this time.

I always get about 12~18fps latency even with RTMP to WebRTC. Would you like to lower the GOP interval to 1 second? That may solve your problem.

**Comment by getroot** [comment]
Try this once. This is our app. We get almost 12fps latency with this. This is also a program for sending in RTMP.

https://play.google.com/store/apps/details?id=com.airensoft.ovenstreamencoder.camera&hl=en

**Comment by swedishdeveloper** [comment]
Hi

I set **GOP** to **1 second** and it decreased the latency a bit. But I still waiting for your RTSP solution. 
Your app works well but it also has some delay, but that's because of RTMP I think.

I want to get the stream near real-time, but that is many jobbing hours I think. I working on my streaming solution and the people that have tested the live stream say that the latency is not so good. Apart from that, I like OME as a streaming engine.

Thanks for your tips.

**Comment by swedishdeveloper** [comment]
Hello again!

Thanks, guys for helping me configure RTSPPull!!
It working very well. My solution was to use a custom RTSP Server that I am pushing the stream to, then I using OME for converting the stream to WebRTC and it works very well! 
You are the best. Now the latency is much better, AMAZING!!

Regards

**Comment by nangavar** [comment]
Hi @swedishdeveloper 

I've reached 150ms of latency with a FPGA encoder using RTSP-Pulling. 
GOP shouldn't increase latency, only increases the time it takes to start streaming, but after it is playing shouldn't have more delays. If you set the GOP below 0,5seg I think you will start experiencing some quality issues in my opinion.

**Comment by swedishdeveloper** [comment]
Yes that is true! If you set GOP to low, you will experience quality issues.
Thanks for you help nangavar

**Comment by getroot** [comment]
The RTSP Pull feature has released in beta 0.10.4.
See https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta

This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by deepsurvey** [comment]
Hi,

So I try to add RTSP but unsuccessfull. 

I am docker-composing OME as an Origin and have no problems there.
In order to intergrate a RSTP source I changed the /misc/conf_examples/Origin.xml
-----------------------------------------
simon@Laplace:~/OvenMediaEngine/misc/conf_examples$ cat Origin.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="6">
	<Name>Simon_OME</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<Bind>
		<Providers>
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
			</RTMP>
			<RTSP>
				<Port>554</Port>
			</RTSP>
		</Providers>




---------------------------------------


According to the Dockerfile the running environment should be copied from /misc/conf_examples/Origin.xml:
----------
## Make running environment
RUN \
        DIR=/tmp/ome && \
        cd ${DIR} && \
        cd src && \
        mkdir -p ${PREFIX}/bin/origin_conf && \
        mkdir -p ${PREFIX}/bin/edge_conf && \
        strip ./bin/RELEASE/OvenMediaEngine && \
        cp ./bin/RELEASE/OvenMediaEngine ${PREFIX}/bin/ && \
        cp ../misc/conf_examples/Origin.xml ${PREFIX}/bin/origin_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/origin_conf/Logger.xml && \
        cp ../misc/conf_examples/Edge.xml ${PREFIX}/bin/edge_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/edge_conf/Logger.xml && \
        rm -rf ${DIR}

-----------------------------------

When I run the docker compose all looks well:

----------
[269/269|100%] Completed.
Removing intermediate container 1dbbde9cc750
 ---> 2da585038c3b
Step 20/26 : RUN         DIR=/tmp/ome &&         cd ${DIR} &&         cd src &&         mkdir -p ${PREFIX}/bin/origin_conf &&         mkdir -p ${PREFIX}/bin/edge_conf &&         strip ./bin/RELEASE/OvenMediaEngine &&         cp ./bin/RELEASE/OvenMediaEngine ${PREFIX}/bin/ &&         cp ../misc/conf_examples/Origin.xml ${PREFIX}/bin/origin_conf/Server.xml &&         cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/origin_conf/Logger.xml &&         cp ../misc/conf_examples/Edge.xml ${PREFIX}/bin/edge_conf/Server.xml &&         cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/edge_conf/Logger.xml &&         rm -rf ${DIR}
 ---> Running in 1d78d3ed0e43
Removing intermediate container 1d78d3ed0e43
 ---> f50a08cc684f

Step 21/26 : FROM	base AS release
 ---> 0ba002d8bc35
Step 22/26 : MAINTAINER  Jeheon Han <getroot@airensoft.com>
 ---> Running in dd51ebfc521a
Removing intermediate container dd51ebfc521a
 ---> 9870ccf99383
Step 23/26 : WORKDIR         /opt/ovenmediaengine/bin
 ---> Running in 21e9c67f61d5
Removing intermediate container 21e9c67f61d5
 ---> 03ff9e8571af
Step 24/26 : EXPOSE          80/tcp 8080/tcp 8090/tcp 1935/tcp 3333/tcp 3334/tcp 4000-4005/udp 10000-10010/udp 9000/tcp
 ---> Running in 57b25fd7a8b3
Removing intermediate container 57b25fd7a8b3
 ---> 64f855444977
Step 25/26 : COPY            --from=build /opt/ovenmediaengine /opt/ovenmediaengine
 ---> d91d139f9fdc
Step 26/26 : CMD             ["/opt/ovenmediaengine/bin/OvenMediaEngine", "-c", "origin_conf"]
 ---> Running in 2e54f59d4a36
Removing intermediate container 2e54f59d4a36
 ---> ebb87c369040


----------------------------------------
If I than dive in the running docker (docker exec -ti ) and look at /bin/origin_conf/Server.xml nothing is changed.
root@827905544ff8:/opt/ovenmediaengine/bin/origin_conf# cat Server.xml 
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="7">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<Bind>
		<Providers>
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
			</RTMP>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000-4003,4004,4005/udp}</Port>
			</MPEGTS>
		</Providers>

		<Publishers>
            



What am I missing here???

Thanks in advance!!

rowdy

**Comment by KVAnton-WEB** [comment]
@theswedishdeveloper 
Sorry, you can help me by showing your configs?
I think I don't understand something .. #274
Thanks
