### ISSUE TITLE
DVR instability and excess CPU usage

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#1354]
**Describe the bug**
I experience steadily increasing memory *and CPU* usage with OME, I suspect there is a bug or something inefficient with the DVR feature. Further, eventually it gets to the point there is spikiness in the CPU usage which goes away after a restart. The spikiness in particular may be a result of our forwarding setup, but I am not sure

You can see in the screenshots the restart I gave OME shortly before the screenshot and around 0500, where memory and CPU usage drop sharply

<img width="723" alt="Screenshot 2023-08-22 at 10 07 55 PM" src="https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/9bf3efb1-5c96-4c8f-881f-e2e22295c02c">

[Server.xml](https://gist.github.com/naanlizard/c6c8f5b4940c3eaf47d414e8e89a6412) - note, 12 hour DVR window

**Expected behavior**
Steadily increasing memory makes sense, but steadily increasing CPU usage and then instability does not

I can't provide logs easily for a little while but I thought I would bring this up. I suspect it should be easy to debug, just start a few dozen streams with my server.xml and wait ~12 hours

**Comment by naanlizard** [comment]
I wasn't sure if this should be a discussion or a bug report, apologies. Please feel free to move if necessary

**Comment by getroot** [comment]
When the DVR is turned on, the segment info list required by m3u8 is maintained in memory for that amount of time. (For reference, the actual segment data is recorded in a file and loaded when needed.) And m3u8 representing 12 hours is very large. If partial segment info is added, it is inefficient because m3u8 is continuously created.

I've been wanting to optimize this to be efficient as well, but I haven't spent the time here yet. I hope to start working on this optimization soon.

**Comment by naanlizard** [comment]
Hmm, if we lower the dvr duration, is there a recommended duration? 6 hours? 8 hours?

**Comment by getroot** [comment]
The service to which I apply DVR is operated with two streams and a 60-minute DVR. You're probably more experienced than me on this one. I will do a detailed analysis of this soon.

**Comment by naanlizard** [comment]
We don’t get the opportunity to adjust settings often but I’ll try 6 hours and see how we do

**Comment by naanlizard** [comment]
Lowered to 6 hours DVR, not really much improved after the first day

<img width="713" alt="Screenshot 2023-08-24 at 10 58 32 PM" src="https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/86950a35-d536-4583-bb4a-b7662f4435e7">

It's possible I'm wrong about the cause, I'll keep this thread up to date on tracking what caused this

**Comment by naanlizard** [comment]
<img width="716" alt="Screenshot 2023-08-30 at 11 41 51 AM" src="https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/bd7f3bfd-a3b9-4974-a2a5-0be42aab8aa4">

Clear improvement, much less instability with a DVR duration of 1 hour. Unsure if I'm running into a resource limit or something or if it's inherent to OME. We'll be switching to OME exclusively Soon:TM: and I can be more confident about my conclusions then

**Comment by naanlizard** [comment]
Possibly related freeze - log here, same settings as above

Streams mostly dropped around 1:12 log time

[omelog.txt](https://github.com/AirenSoft/OvenMediaEngine/files/12695857/omelog.txt)

**Comment by getroot** [comment]
This is unrelated to DVR, and upon examining the logs, it seems to be the same issue as before.
https://github.com/AirenSoft/OvenMediaEngine/issues/1325

I thoroughly analyzed the code in that section while resolving that issue. Therefore, before I proceed with additional in-depth investigation, I'd like to know the version you are currently using. The patch for this issue was included in version 0.15.15, and I recommend upgrading to the latest version, 0.15.16.

**Comment by naanlizard** [comment]
Ah my mistake, this is 0.15.14, I'm sorry about that. Thank you as usual for your hard work and quick responses getroot

**Comment by naanlizard** [comment]
We've put this on the backburner as while we are using OME exclusively now, there are other issues more urgent to solve. Once those are done, we'll keep investigating this if it keeps happening

**Comment by naanlizard** [comment]
Haven't seen this happen again - will close for now
