### ISSUE TITLE
WebRTC ICE are not generated properly

### ISSUE THREAD

**Issue by spartanz51** [AirenSoft/OvenMediaEngine#136]
Hello, 
I saw that the ICE are build and generated. But they should be gathered from STUN, and we should be able to use a TURN for example.

`candidate:0 1 UDP 50 172.17.0.2 10004 typ host`

By the way, the ufrag is missing. Some webrtc implementations reject this ICE format. We can hardcode it but it's better to gather real ICE and respect the standard

Regards

**Comment by getroot** [comment]
We follow the format that ufrag is included in SDP. Please share if you have the latest standard link to it.

**Comment by spartanz51** [comment]
The main problem is that ICE are not gathered, but generated: It may use STUN and TURN to purpose real candidates, and NAT solutions

I have error while trying to add this ICE to the module https://github.com/node-webrtc/node-webrtc
It says: `Error: Failed to set ICE candidate.`

`{
  candidate: 'candidate:0 1 UDP 50 172.17.0.2 10005 typ host',
  sdpMLineIndex: 0,
  sdpMid: '0'
}
[Error: Failed to set ICE candidate.]
`

Remote SDP is already set, answer is already sent. Using an SDP offer and ICE from browser works fine. 
But using this ICE is causing problem

Regards

**Comment by getroot** [comment]
We assume that OvenMediaEngine works on a public network as it is a streaming server, not WebRTC for P2P. If you are operating on a private IP such as AWS, you can use the method of putting the IP directly into IceCandiate. Check the following url.
https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#configuration

We are considering extracting real IP through STUN for more convenient use, but we will not use TURN. TURN is enough to use in PLAYER. (Because it is a public network)

**Comment by spartanz51** [comment]
I see, thanks for clarification
regards
