### ISSUE TITLE
Native LL-HLS on Apple devices falling back to regular HLS

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1510]
**Describe the bug**
Apple devices which do not support HLS.js are falling back to regular HLS instead of native LL-HLS playback.

**To Reproduce**
Start an LL-HLS stream and view it from an iPhone or another device which does not use HLS.js for LL-HLS - it will not have the same low latency as HLS.js / OvenPlayer.

**Expected behavior**
In the past, native playback of LL-HLS worked well with 2-3s latency but now it seems to fall back to regular HLS with 15-20s latency instead

**Server (please complete the following information):**
OME 0.16.4 on Ubuntu Docker

**Player (please complete the following information):**
 - Device: iPhone or Safari on macOS using direct playback of .m3u8
 - OS: iOS 17 / macOS Sonoma

**Additional context**
I'm not sure whether this is an issue with the latest Apple OS or OME 0.16.4. Is anybody else able to reproduce the issue?

**Comment by getroot** [comment]
For a long time, when playing directly in Safari, there has been an intermittent problem where playback starts in legacy HLS due to a slow network or unknown reasons, but in that case, if you move the seek bar below to the latest, playback starts in LLHLS again. There seems to be a condition where Safari starts playing LLHLS in legacy mode under certain conditions. I don't think this has anything to do with OME 16.4.

The Safari browser is actually still in LLHLS, so it appears to still be in beta. What I experienced was that until iOS 17.1, there was a problem with ABR playing only at the lowest bitrates, and that was resolved in 17.2.

**Comment by mbakumenkov** [comment]
On my Iphone, the problem with low LLHLS bitrate in safari is not reproduced on 17.2 beta 2, but it is reproduced on the 17.2 release, and also not reproduced on the 17.3 release. Based on this, I think that they finally released it in 17.3 :)
