### ISSUE TITLE
Video Streaming stuttering and a few other questions

### ISSUE THREAD

**Issue by krishnakanthpps** [AirenSoft/OvenMediaEngine#153]
**Describe the bug**
I am trying to send a live stream video to the Ultra Low Latency Demo Video Player via RTMP Camera and also a similar one hosted on cloud myself. For both of these.. when I send a live RTMP stream, the latency increases to around 5 -10 seconds, sometimes stops.. and sometimes the RTMP Camera says video stopped.  And if it works, it works only for 1 user and not more than 1 user. 

I have not changed anything in terms of configuration except for trying to send video via RTMP Camera app. The OvenStreamEncoder doesnt even work. It says incorrect address even for the address to OvenMediaEngine specified on the demo page of OvenPlayer. 

Some of my other questions:

What should be the configuration to handle 100-1000 users. Ideally I want to livestream from the browser itself, but if it is not possible, then via OBS from desktop to a web application. 

This is what I plan to do : 

OBS --> RTMP --> OME --> OvenPlayer. 

So what should be my hardware configuration to have ultra low latency with 1000-10000 people viewing. 

What should I do to overlay chat on the OvenPlayer especially on mobile. 

Regards,

**Player (please complete the following information):**
 - Device: ASUS M1
 - OS:  Android 8
 - Browser : Via RTMP Camera App
 - Version : NA

**Additional context**

**Comment by getroot** [comment]
1. What is RTMP Camera? Are you sure you tried to remove the B-frame and send it out? Please read the https://airensoft.gitbook.io/ovenmediaengine/ manual carefully.
2. What are your server performance specifications? (CPU Core, Ram, Network)
3. If there is a problem, upload OME's Server.xml and /var/log/ovenmediaengine/OvenMediaEngine.log.
4. What was the RTMP sending address? What was the WebRTC playback address?
5. To accommodate more viewers, the Origin-Edge structure must be used. Please refer to the manual.
6. http://demo.ovenplayer.com/ome_demo.html If you used here, it may feel slow because the server is installed in Seoul.
7. Overlaying the chat over the player is the area of ​​the application. It is not a feature of OvenPlayer.
8. Browser: Via RTMP Camera App is not understood. The browser is called RTMP Camera App, what is it? Didn't you use something like chrome or firefox?

**Comment by krishnakanthpps** [comment]
1. RTMP Camera : https://play.google.com/store/apps/details?id=com.miv.rtmpcamera&hl=en_IN

2. 4Core 16GB 50Gbps. It is on Oracle Cloud.

3. It was Seoul server's OME Server for which I wont have access.

4. RTMP Sending Address : rtmp://dev2.airensoft.com/app / stream

5. Let do that.

6&7 : Sure. let me try something else.

8. I am not sure how to stream to rtmp from chrome or firefox. 

9. I will share the error when I test again. 

Also.. 

My installation of OME failed so used the Seoul server to send RTMP to OvenPlayer. 
Not sure how I can remove the B frames. The OvenStreamEncoder didnt even connect to the RTMP server in Seoul.

I was not able to do a WebRTC broadcast from the browser. Any suggestion on how I can get WebRTC broadcast from browser to OME?

**Comment by getroot** [comment]
http://demo.ovenplayer.com/ome_demo.html If you are testing here, please test using OBS on your PC to see if the problem is due to the encoder or nettwork. Please refer to https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder for information related to OBS settings.
And if you tell us the result, it will be very helpful in solving the problem.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
