### ISSUE TITLE
Dash playable in vlc but not in OvenMediaPlayer

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#162]
Actually i am trying to use Dash-ll in your demo player and it didnt playes anything. Vlc playes the files without any problem.

http://95.217.118.51:8080/app/live/manifest.mpd

http://95.217.118.51:8080/app/live/manifest_ll.mpd

Its the Docker Version of ome which is delivering these files and my obs Settings are these out of your howto...

many thanks for your help

**Comment by getroot** [comment]
Yes this is a known bug.  Under certain conditions (the exact conditions are not yet known), mpeg-dash does not play on the web, and we are analyzing it.  Thanks for the report.

**Comment by getroot** [comment]
We're sorry, but with the release of LLHLS, we have decided to no longer update LLDASH. Because LLHLS has better performance and compatibility, we decided it was a better decision for everyone to focus more of our energy on it.

Instead, we will continue to focus more on LLHLS and WebRTC. Thanks for your contribution.
