### ISSUE TITLE
cache setting in ome??

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenMediaEngine#167]
I want to set the cache in ome.
Is it possible?

**Comment by getroot** [comment]
Please explain clearly the cache function you are talking about.

In OvenMediaEngine, HLS and MPEG-DASH keep chunks for a period of time. (This is like a cache.)
But, because WebRTC processes data in real time, the existence of a cache function only increases latency. So OvenMediaEngine doesn't keep any data in WebRTC.

Which cache do you want? (In live streams, cache is mostly meaningless.)

**Comment by getroot** [comment]
This issue has not been updated for a long time, so I close the issue. If you would like to continue discussing this issue, please reopen it.

**Comment by jys923** [comment]
A fast hardware called U2 is added to transmit real-time stream data from U2.

**Comment by getroot** [comment]
I can't understand what you mean.
