### ISSUE TITLE
How to enable GPU in FFMPEG in OME?

### ISSUE THREAD

**Issue by alex-jhones** [AirenSoft/OvenMediaEngine#174]
Hi 
I want to use the GPU to reduce the latency in transcoding of ome, what setting do I need?
Currently, it is about 0.5 seconds, but it is estimated that CPU-based transcoding will cause a lot of delay.
And is there any other way to lower the delay even further?

**Comment by getroot** [comment]
It becomes possible only when we develop.
It is listed on #23 , but we are too busy to proceed with it. We are looking forward to doing that too quickly. Thanks for the comments.

**Comment by alex-jhones** [comment]
I am really interested in the delay problem. If you can give us some information to experiment with delay reduction, we'll give it a try.

**Comment by getroot** [comment]
Let's share what we've been analyzing latency in the meantime. (It's still in progress, so it's not complete.)

OBS has its own delay. That's the time it takes to mux video and audio, we understand.

And in fact, OvenMediaEngine's transcoder doesn't have a significant effect on the delay (probably only 2-4 fps delay occurs in the OME transcoder). That delay occurs a lot due to the time difference between A-V. The WebRTC player has its own buffer (approximately 300ms for Chrome) and uses it to sync the AV, which causes the delay. If the encoder cuts the A-V finely and sends it at the same time, this is also a way to reduce the delay. But most encoders send video first and then audio.

The key is the encoder. The encoder's own delay needs to be reduced, and the A-V should be cut and sent almost simultaneously.

So we wanted to reduce the delay even further, so we developed an Android broadcast app and tested it with it. (This is called OvenLiveEncoder, and the version on the store is not a delay-reduced version.) We have confirmed that this app reduces the delay to 9 fps. This will be updated on the Play Store soon. (Probably within two months)

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by OlegGavrilov** [comment]
@getroot is there any progress on this?

**Comment by getroot** [comment]
When this is updated, we will post information on #23 .
