### ISSUE TITLE
low latency dash constantly stops when using as edge

### ISSUE THREAD

**Issue by aaron-vince** [AirenSoft/OvenMediaEngine#182]
**Describe the bug**
low latency dash constantly stops when using as edge. upon checking response headers manifest_ll.mpd keeps getting a "Status Code: 202 Accepted" but when using rtmp as provider on the edge everything runs fine
![image](https://user-images.githubusercontent.com/14003067/90994831-a7e3fb00-e5ec-11ea-8932-98e1bcb9d7cf.png)

**To Reproduce**
1. Set Server.xml as follows 'edge and use ovt as provider.'
2. With Encoder use obs same config as docs
3. play lldash video you will notice video keeps stopping 

**Expected behavior**
video should not constantly stop

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/5115349/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: centos 7
 - OvenMediaEngine Version:0.10.7

**Player (please complete the following information):**
 - Device: pc
 - OS: windows 10
 - Browser Microsoft Edge 
 - Version 84.0.522.63 (Official build) (64-bit)

**Comment by getroot** [comment]
Please share your Server.xml and Full log (especially the log at the moment of error).

**Comment by dimiden** [comment]
@aaron-vince
OME Edge is not always connected to Origin, but only when it plays stream on Edge.
Immediately after the connection established, Edge returns ```202 Accepted``` because it does not have enough data to create an LL-DASH segment, and after ```segment_duration``` or later, it returns ```200 OK```.

This issue occurs because OME is not HTTP reverse proxy, and if this behavior is problematic, it is recommended that you use another HTTP reverse proxy server as Edge.

**Comment by getroot** [comment]
We're sorry, but with the release of LLHLS, we have decided to no longer update LLDASH. Because LLHLS has better performance and compatibility, we decided it was a better decision for everyone to focus more of our energy on it.

Instead, we will continue to focus more on LLHLS and WebRTC. Thanks for your contribution.
