### ISSUE TITLE
Update dockerfile to match prerequisites.sh

### ISSUE THREAD

**Issue by OlegGavrilov** [AirenSoft/OvenMediaEngine#213]
Currently, Dockerfile is lagging behind regular compile story, for example, there is no libx265 library used, and some stuff related to "jpeg,png" muxers of ffmpeg.

Propose:
Maybe Dockerfile should use prerequisites.sh for compiling OME? So the docker image will be always updated with latest features of OME.

I can do the PR if this approach is OK with everyone.

**Comment by getroot** [comment]
That's a great idea.
prerequisites.sh and Dockerfile are pretty much similar, but we're managing them separately. (At first we made Docker based on alpine, and I think there may be differences in the future.)

The slow update of the Dockerfile is because only the released version is managed as a docker image. We will also update the Dockerfile when 0.10.9 is released.

Thanks for your suggestion.
