### ISSUE TITLE
OvenMediaEngine with AWS C++ SDK

### ISSUE THREAD

**Issue by ruifigueirinha** [AirenSoft/OvenMediaEngine#214]
I have been trying to include the AWS C++ SDK in OME but without success. The problem that I found is when linking with OpenSSL libraries generated by the AWS SDK. I am trying to upload the TS segments from the HLS packetizer into an S3 bucket.

Do you have any experience in including this SDK into OvenMediaEngine?

Thank you

**Comment by ruifigueirinha** [comment]
This is the compilation result

####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 8
   - GCC version             : 7.5.0
   - Build option            : DEBUG
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig:/usr/local/lib/pkgconfig
   - Total Projects count    : 42

[1/3| 33%] Preparing directories...
[2/3| 66%] [executable] Linking OvenMediaEngine... => bin/DEBUG/OvenMediaEngine
//usr/lib/x86_64-linux-gnu/libcurl.so.4: undefined reference to `SSL_CTX_set_keylog_callback@OPENSSL_1_1_1'
collect2: error: ld returned 1 exit status
core/build_executable.mk:7: recipe for target 'bin/DEBUG/OvenMediaEngine' failed
make: *** [bin/DEBUG/OvenMediaEngine] Error 1

**Comment by getroot** [comment]
OvenMediaEngine currently uses OpenSSL 1.1.0g. And we haven't used the AWS SDK yet.

Are you trying to upload TS to S3 in order to use CloudFront? If so, put the HLS address of OvenMediaEngine in the origin setting of CloudFront and it should work. Is there any reason to upload to S3? If there is a reason, I recommend the following method to you. (Maybe this will be easier.)

-Setting up a tool that syncs files in the local directory and S3 (for example, https://www.cloudsavvyit.com/577/how-to-sync-files-from-linux-to-amazon-s3/)
-Developed a function to save TS chunk as a local file in HLS Publisher of OvenMediaEngine

**Comment by ruifigueirinha** [comment]
Thank you for the suggestion. I am trying to use AWS for stream archiving purposes. An alternative to using the SDK was to use the AWS CLI. I would save the chunks to disk and upload them using AWS CLI. However I wanted to eliminate constant I/O to disk so this may not be the best solution.
