### ISSUE TITLE
encrypted streams?

### ISSUE THREAD

**Issue by ihubgit** [AirenSoft/OvenMediaEngine#243]
Hi, I'm new to the software. Does it handle encrypted streams?

**Comment by getroot** [comment]
Please explain in more detail

**Comment by ihubgit** [comment]
Well, does it encrypt the video stream when having a videoconference over the Internet ?

**Comment by ihubgit** [comment]
was that too hard a question ?

**Comment by basisbit** [comment]
@ihubgit OvenMediaEngine does video streaming, not really videoconferencing. Anyways, OvenMediaPlayer supports HLS and DASH and RTPS (using STUNNEL) for encrypted transmission of video streams. So if you only want one-way live-video-streaming (similar to YouTube or Twitch), then the answer to your question would be yes.

**Comment by getroot** [comment]
This is a very broad question because OvenMediaEngine supports a variety of protocols.

As the @basisbit commented, this is a streaming server for broadcast, not a system for conferences. (What you want is probably a system like Janus.)

And WebRTC basically uses DTLS, SRTP to encrypt the stream. (Otherwise, the browser does not play.) HLS and MPEG-DASH are encrypted using tls. With WebRTC signaling, we are using web socket, and tls can be applied here as well.

RTSP, MPEG-2 TS, RTMP inputs require different discussion.

Please read the manual.
https://airensoft.gitbook.io/ovenmediaengine/streaming/tls-encryption

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
