### ISSUE TITLE
Adjust WebRTC UDP MTU?

### ISSUE THREAD

**Issue by command-tab** [AirenSoft/OvenMediaEngine#258]
**Is your feature request related to a problem? Please describe.**
When streaming under certain conditions, WebRTC playback is choppy. If I adjust the MTU of the OME host, playback is smooth.

**Describe the solution you'd like**
Ideally, I'd be able to set the desired WebRTC UDP MTU in software, perhaps in the `Server.xml` configuration.

**Describe alternatives you've considered**
I can set the MTU on the OME host's ethernet adapter, but it does not persist across reboots.

**Comment by getroot** [comment]
What was your mtu?
And what value made the playback smoother?

Currently, OME generates UDP packets of about 1400 bytes. You have to use jumbo frames in order to exceed 1500 bytes, you know, this cannot be used in real world.

We have experienced an environment with high internet speed but severe udp packet loss before. In order to realize smooth playback even in such an environment, we installed the TURN server on the same server as OME, the Player and the TURN server are connected by TCP, and the TURN server and OME are configured to communicate with UDP through a loopback interface. And in this environment, we have confirmed that all viewers play smoothly without problems. In this environment, one server is currently sending streams to 1000 concurrent users.

So we are currently embedding Turn server in OME. This is a performance advantage and will be more convenient to use than using an external turn server. In other words, viewers will be able to watch with WebRTC/Turn/TCP. And this can be selected by server or player settings.

I think your problem could be solved with WebRTC/(Turn)/TCP. What do you think? This feature will be released in February.

**Comment by command-tab** [comment]
Ah, yes, the MTU was originally 1500, but works much better at 1400.

I'm looking forward to the February release! With stream recording, API server docs, and an embedded TURN server, it's shaping up to be an awesome release 👏🏻 

Thank you for your work ❤️

**Comment by dbContext** [comment]
You should be able to persist the MTU through the network interface configuration.

CentOS / RHEL / Fedora:

`MTU="1400"` within /etc/sysconfig/network-scripts/ifcfg-eth0

Ubuntu / Debian:

`mtu 1400` within /etc/network/interfaces

**Comment by command-tab** [comment]
I will do that. Thank you!
