### ISSUE TITLE
100% CPU on a single core

### ISSUE THREAD

**Issue by Baa14453** [AirenSoft/OvenMediaEngine#285]
**Describe the bug**
One of my cores always uses 100% CPU while the stream is running.

**To Reproduce**
1. Set Server.xml as follows:
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5984395/Server.xml.txt)

2. With Encoder OBS 26.0.0-rc2-17-g2963b3b8 (64 Bit)

3. See:
![image](https://user-images.githubusercontent.com/9057997/107997946-eecf0e00-6fdb-11eb-8799-8091580db5df.png)

**Expected behavior**
All processing would be distributed between cores.

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/5984379/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - OvenMediaEngine Version: 0.11.0
 - Branch: Release

**Additional context**
Tried reducing the number of transcoding streams to only 1 instead of 3 but the issue remained :thinking: 
Video playback is choppy on the higher qualities but unsure if this is my bandwidth yet or not.

**Comment by getroot** [comment]
It seems that the x264 encoder uses 100% of one core.
Would you like to test it by setting _context->thread_count in the file below to 0?

https://github.com/AirenSoft/OvenMediaEngine/blob/28175e3e306bfde60eee2f71e8df5b2911c82c02/src/projects/transcode/codec/transcode_codec_enc_avc.cpp#L74

Video playback is choppy on the higher qualities: This may be because the encoding is not 1x. Otherwise, it could be due to UDP loss. If so, try testing with #287.

**Comment by getroot** [comment]
I also tested, and even if the thread_count is set to 0, I confirmed that one core is used at 100%. It seems to be an issue related to x264, so I'll check this out a bit more.

**Comment by kwonkeukhan** [comment]
@Baa14453 

The AAC decoder was using unnecessary CPUs. The problem has been solved, so please test it again in the latest master version.

Thanks to you, I solved a serious bug in OME. 👍

**Comment by Baa14453** [comment]
Looks good thanks for fixing so fast :D
![image](https://user-images.githubusercontent.com/9057997/108067449-b4578680-7058-11eb-99e6-79285b09c7ef.png)
@getroot I will test with #287 later today :+1:

**Comment by getroot** [comment]
Good
