### ISSUE TITLE
Pass custom arguments to transcoding stream

### ISSUE THREAD

**Issue by Baa14453** [AirenSoft/OvenMediaEngine#286]
**Is your feature request related to a problem? Please describe.**
I'd like to customise h264 profile and other settings.

**Describe the solution you'd like**
A tag in the encodes that lets me pass arguments directly to ffmpeg e.g.

```
<custom-arguments>
    <profile>high</profile>
    <tune>zerolatency</tune>
</custom-arguments>
```

**Describe alternatives you've considered**
I have considered meditating on the issue and transcending past mere video entertainment :pray: 

**Additional context**
A similar product Simple Realtime Server (SRS) implements something like this with the vparams option, the config for transcoding looks like this:
```
        engine ff {
            enabled         on;
            vfilter {
                vf scale=w=640:h=360:force_original_aspect_ratio=decrease;
                loglevel       debug;
            }
            vcodec          libx264;
            vbitrate        1000;
            vfps            30;
            vwidth          0;
            vheight         0;
            vthreads        4;
            vprofile        high;
            vpreset         superfast;
            vparams {
                g       60;
                tune    zerolatency;
                vlevel  3.1;
            }
            acodec          aac;
            abitrate        128;
            achannels       2;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]-HLS/[stream]_360;
        }
```

**Comment by getroot** [comment]
good. This feature was already in our backlog.
We will develop this feature when our high priority work is done.

**Comment by getroot** [comment]
Sorry for the late update.

We use not only x264 as the encoder, but sometimes openh264 as well. In addition, it uses VP8, hardware encoder, etc. Therefore, we decided that it is not good for the server operator to put the parameter in accordance with ffmpeg's H.264.
Instead we started adding normalized values like presets.

https://airensoft.gitbook.io/ovenmediaengine/transcoding#encodes

We plan to add normalized options so that they can be used by all encoders if we think they are additionally necessary.

Thank you for your suggestions and contributions.
