### ISSUE TITLE
Feature Request: Implement RTP Header Extension to control Playout Delay

### ISSUE THREAD

**Issue by S3-sim** [AirenSoft/OvenMediaEngine#289]
Hi,

I am proposing implementing the RTP header to contol playout delay. Implementing this would allow you to define a fixed playout delay and eliminate the adaptive delay that WebRTC tries to calculate based on inter-packet and jitterbuffer delay which can cause cause playback speed inconsistencies. 

I theorize it would also potentially allow for the new TCP relay to resend packets before the browser emittes the section of data that requires retransmission on high latency connections.

Here is the document for this RTP header. http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

**Comment by getroot** [comment]
Hello

Thanks for the great suggestion.
There are still many high-priority tasks left, so we are not working on non-standard features yet. However, when I study again this time, it seems that the playout delay function is supported by Chrome, Safari, and Firefox in the end, so it can be seen as a de facto standard. So I would like to discuss adding this feature.

Here is my opinion.

First of all, I think it has no effect on TCP retransmissions. This is because TCP retransmissions are already handled by the pre-application layer.

Second, I'm curious how to use this feature in OME and how to apply it.
As mentioned in the article above, it's a good idea to set the latency to 0 for interactive streaming and a fixed delay (100ms) for movie streaming to make playback smoother. This should depend on the type of broadcast content when creating the stream. So how can OME apply this? When applied to an application setting, it affects all streams below it, so it can only be used if you have control over which streams are created. However, in this case, you can use the player's "PlayoutDelayHint" function to more easily implement the same functionality. Do you have any other thoughts?

Any more specific ideas on this feature would be appreciated.

**Comment by S3-sim** [comment]
Hey @getroot, sorry for the delay in replying to this.

I believe it will not impact TCP retransmissions directly for the reasons you outlined, but the side effect of TCP retransmissions is the potential increased latency of receiving those packets. This feature, if set high enough could help further increase the reliability of the stream playback on non-optimal connections.

I was not aware of the playout delay hint on the client end. If that was settable as an option within Ovenmediaplayer, I would assume that would provide the same functionality. This would probably be the preferred method as it would potentially allow to user to update the PlayoutDelayHint on a per-client basis to try and offset the effects of bad network performance. Is this feature something that would updatable without destroying the current player and re-initializing it?

It looks like PlayoutDelayHint is widely supported as well as far as I can tell. I don't think implementing the RTP Header Extension will provide any advantage over the client side function.

**Comment by S3-sim** [comment]
@getroot 

I just found what looks like the ability to set the PlayoutDelayHint in OvenPlayer, but I don't see any mention of it in the documentation.

https://github.com/AirenSoft/OvenPlayer/blob/8a56256d4f38a14566006661164e6441a9d87f79/src/js/api/provider/html5/providers/WebRTCLoader.js#L334-L348

I have also created a post in the OvenPlayer git asking about this feature as it seems like that is the faster way to implementing the feature.

**Comment by S3-sim** [comment]
I found that the playoutDelayHint is already settable with OvenPlayer by using the following option when initializing the player.

webrtcConfig: {
        playoutDelayHint: " x "
    }

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by getroot** [comment]
I got curious about how this works, so I implemented this experimentally. As a result of the experiment, Chrome only seems to work with this feature, and it doesn't seem to work as well as expected. (A/V sync is broken at the beginning of playback because only video is delayed, etc.)

However, it may be useful to turn off the adaptive delay function by setting Min and Max to the same value of k.

You can set it up as follows.

```
<Publishers>
...
<WebRTC>
...
<PlayoutDelay>
<Min>400</Min><Max>400</Max>
</PlayoutDelay>
</WebRTC>
```
