### ISSUE TITLE
Difference in Benchmark

### ISSUE THREAD

**Issue by nicenoz** [AirenSoft/OvenMediaEngine#296]
Hi~!

I'm trying to load test. 
In your benchmark site, In the environments of output bitrates 2Mbps, 8 threads, and 1600 Max viewers, publish was normal.
But actually, When I tried to play in the same environment, The video and audio output were unnormal.
that is, streaming is a break in about 600 viewers, so I want to know if I use the wrong configuration. 
Finally, As your benchmark, I want to make up the same environment.

Add my Application configure. Thank you.

```
<Applications>
                                <Application>
                                        <Name>doublemedia</Name>
                                        <!-- Application type (live/vod) -->
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>

                                                                <Audio>
                                                                        <Codec>opus</Codec>
                                                                        <Bitrate>128000</Bitrate>
                                                                        <Samplerate>48000</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>
                                                                <!--
                                                                <Video>
                                                                        <Codec>vp8</Codec>
                                                                        <Bitrate>1024000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                </Video>
                                                                -->
                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
                                        <Providers>
                                                <OVT />
                                                <RTMP />
                                                <MPEGTS>
                                                        <StreamMap>
                                                                <!--
                                                                        Set the stream name of the client connected to the port to "stream_${Port}"
                                                                        For example, if a client connets to port 4000, OME creates a "stream_4000" stream
                                                                -->
                                                                <Stream>
                                                                        <Name>stream_${Port}</Name>
                                                                        <Port>4000,4001-4004</Port>
                                                                </Stream>
                                                                <Stream>
                                                                        <Name>stream_4005</Name>
                                                                        <Port>4005</Port>
                                                                </Stream>
                                                        </StreamMap>
                                                </MPEGTS>
                                                <RTSPPull />
                                        </Providers>
                                        <Publishers>
                                                <SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
                                                <OVT />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                                <HLS>
                                                        <SegmentDuration>1</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </HLS>
                                                <DASH>
                                                        <SegmentDuration>1</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
            <Url>*</Url>
                                                        </CrossDomains>
                                                </DASH>
                                                <LLDASH>
                                                        <SegmentDuration>1</SegmentDuration>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </LLDASH>
                                        </Publishers>
                                </Application>
                        </Applications>
```

**Comment by getroot** [comment]
I need more details to answer this. There are countless things that determine a server's performance beyond CPU and RAM. You must provide all the necessary information.

1. Have you configured your system with Origin-Edge structure? Origin does OPUS encoding, which affects performance. Play with Edge.
2. Does your network environment support 10Gbps? A 600 viewer with 2Mbps will use about 1Gbps. Check if your network is 1Gbps. And check out the PPS.
3. Is live input using OBS? If the encoding is set to VBR, the traffic may increase in an instant. You should also check the settings of the encoder.
4. Check CPU and memory when 600 viewers are connected. At that time, is the system using 100% CPU?
5. What version of OME are you using?
6. Are there any abnormal messages in the OvenMediaEngine.log log?
7. What did you use the Viewer Simulator? Are the resources and network (10Gbps) of the Viewer simulator sufficient?
8. Did you check that it plays normally in about 300 viewers?
9. What does "streaming break" mean? Are you saying that playing is choppy? Or is it disconnecting?
10. Is UDP packet loss the cause? Or is the server unable to send data?
11. Have you set up enough kernel network settings? This is very important. See documents like this: http://www.linux-admins.net/2010/09/linux-tcp-tuning.html Both UDP and TCP sockets need enough buffers.

**Comment by nicenoz** [comment]
1. There is a problem in Origin-edge Structure. If the version of origin differs from the version of edge, I can't play in the edge. I made up the 0.10.11 version of the origin server and 0.11.0 version of edge, it is incompatible with each other.
2. It's okay, I have 10Gbps network environment.
3. In OBS setting, I set up CBR, doesn't it matter?
4. In checking my cpu usage, it increase up to 765% in 2Mbps bitrate and 600 viewer.
5. As having some problem, I make up the same version in origin-edge..
6. There is no problem in log.
7. It's sufficient to simulate.
8. In 300 viewers It plays normally well.
9. It means choppy.
10. I don't know sorry.
11. Thank you for your advice, I'm studying kernel networking settings.

**Comment by getroot** [comment]
As your OME is using most of the CPU(8 core, right?), 600 is the limit in its current state. You can check CPU usage by process-thread. Capturing and uploading it makes it easier to analyze the problem.

1. Are you using the cloud?

2. Set it to Origin-Edge. You must use version 0.11.0 for both Origin-Edge. Are there any reasons for using different versions? Origin does the encoding, so it uses a lot of CPU resources.

3. Disable HLS, DASH, LLDASH.

4. Describe your simulator. Which one and how are you using it?

5. Are you playing WebRTC over TCP? (transport=tcp) or udp?

**Comment by nicenoz** [comment]
1. No, I don't use cloud service, I'm served the similar networking environment VM service in IDC corp.
2. Origin server is real server, Origin-edge structure is already made up.
    I think you must notice user in your app must set up same version in github. 
   It spends many times because there is no notice in app. And there are some problem in scaling up service such as 
   rolling update.
3. I already disalbe that options.
4. I use your app, oventestor. previously, I downloaded the app, in your github. But I don't find out the app after that.
5. I use WebRTC and UDP.

**Comment by basisbit** [comment]
in that case, the used CPU and the virtualization environment will probably make the difference. The AWS server which was used for the mentioned test has 8 dedicated CPU cores (not CPU threads) of a very recent CPU with high single-threading and high multi-threading speed.

**Comment by basisbit** [comment]
when using the origin + edge setup, you can have one or two (for HA) origin servers, and for example 30 edge servers which all pull the video stream from the origin stream and then each distribute the video stream to the clients. Thus, with your setup, you could for example handle approximately 30*500 = 15.000 concurrent users with 30 such edge servers.

**Comment by getroot** [comment]
Please provide all the information you can give us so we don't bother each other.  

If OME is using all of the server's resources, a log indicating that the queue is overflowing will appear.  You said there were no abnormal logs, so the server still has room.  Nevertheless, since it is over 700%, there is only a very small margin, so there is a high possibility that basisbit's opinion is correct.  

I think PPS limit may be caused of your issue.  In fact, AWS also provides 10 Gbps network, but if it calculate pps based on 1400 bytes, it cannot exceed 5 Gbps. And this is of very high quality, and IDC's regular VMs are mostly much lower numbers than this.

Oh my god, You should have told me this from the beginning. OvenTester is an unstable version.  OvenTester doesn't behave the way you think and you can't test OME's performance with it.  How many physical servers did you run OvenTester on?  In the past, someone wanted to contribute to the tester, so I just released a version in development, but I couldn't proceed with it, so I put it down now.

Finally, the fact that the minor version is different means that there are several changes and many bug fixes.  Lots of bugs are being fixed, so check the commit log if you want.  If there is a change in ovt it is most likely incompatible.

**Comment by basisbit** [comment]
two more cents on the topic:
If low latency is not that important, you can try using the HLS to transfer 5 second chunks from the edge server to the viewer, that requires less CPU time, so that bandwidth is probably going to be the bottleneck.
Also, it would be nice if OME supports specifying a cipher suites order for the TLS connections in order to further reduce CPU usage by choosing cipher configurations that work best for your used hardware and its hardware acceleration capabilities.

You can do a "rolling release" by starting a new origin server, adding new edge server instances, also send the video stream to the new origin server, test the setup, and then slowly add the new edge servers to your load distribution setup. Thus, a rolling update can be done with OME.

**Comment by nicenoz** [comment]
exactly which information you said do you want? I will give you informatio as soon as possible.
I know tester app is unstable version, I use the app in order to traffic testing.

**Comment by getroot** [comment]
It is very difficult to measure the performance of OME with the existing OvenTester. That's because OvenTester performance is limited (OvenTester is less performant than OvenMediaEngine). With OvenTester you can simulate about 250 clients at the same time on a good server. (Of course, we cannot guarantee how it will behave depending on the environment either.)

Also you should make sure your server's CPU is dedicated 8 core. And you need to measure your network's PPS limit. You also need to verify that the kernel's socket buffer settings are sufficient.

There are a number of variables that drive maximum server performance. When raising an issue, provide enough information about it so that we can analyze it easily. (It would have been nice if you provided all of the questions I asked for this thread in the first place-your hardware type, network information, simulator type and method, etc.)

Of course, measuring the maximum performance of a server is very difficult. When you get enough information, please give us specific suggestions on how to improve OME's performance. (Currently, OME is serving 3,000 people per server (of course, a system with much higher performance than 8 core) in major commercial services.)

Feel free to create an issue if you would like to share your analysis, reproduce a low-performing situation, or have another suggestion.
