### ISSUE TITLE
Too many playlists loaded per segment - HLS

### ISSUE THREAD

**Issue by Shachar9999** [AirenSoft/OvenMediaEngine#358]
We created an HLS live 4k stream with OvenMediaEngine 0.11.2 using OBS 26.1.1. 
When we start playing the stream multiple playlist files are being loaded per 1 segment for the first few minutes as you can see below: 
 
![image](https://user-images.githubusercontent.com/83763432/117293054-9a6c5980-ae79-11eb-95fa-607f2bcc0e95.png)

After few minutes we are receiving 1 manifest per 1 segment (as expected): 

![image](https://user-images.githubusercontent.com/83763432/117293176-c4be1700-ae79-11eb-9f33-a513b88587a5.png)

**We are trying to understand why multiple playlist files are being loaded although the segments list hasn't changed in between?**

**OvenMedia server.xml:**
SegmentDuration: 6
SegmentCount: 10

**OBS settings:**
Output Mode: Advanced
Encoder: NVIDIA NVENC H.264
Rate Control: CBR
Bitrate: 20000 Kbps
Keyframe Interval: 1
Present: Low-Latency Quality
Profile: High
GPU: 0
Max B-frames: 0
Base (Canvas) Resolution: 3840x2160
Output (Scaled) Resolution: 3840x2160
Common FPS Values: 59.94 (depends on the video's FPS)

**Comment by basisbit** [comment]
The playlist file requests are created by the client in the browser, not by OvenMediaEngine. I'd guess you used hls.js on the client to play the stream. If yes, then that should be the normal / usual behavior because it does not know exactly when the next segment file will be available and thus has to guess the timing. It also does not know how consistent / reliable the network connection is. Thus, hls.js requests playlist files with smaller time distance initially, and when it is able to roughly guess when the next .ts file should be available and listed in the playlist.m3u8, it will eventually only do one (or occasionally two) requests per segment.

**Comment by Shachar9999** [comment]
Thank you for your quick reply! This is indeed the case. Playing the above in HTML5 player did play it well! 👍 
Thank you!
