### ISSUE TITLE
Issue  with 0.12.0

### ISSUE THREAD

**Issue by diegocisneros1967** [AirenSoft/OvenMediaEngine#376]
**Describe the bug**
Since the latest version, it is very difficult to connect to the stream in all protocols, and Webrtc is very unstable. If you add option ?transport=tcp does not  connect, without it work, but not well.

[crash_20210522dump.docx](https://github.com/AirenSoft/OvenMediaEngine/files/6527146/crash_20210522dump.docx)
![Directory](https://user-images.githubusercontent.com/84642882/119240786-c0bd1500-bb5a-11eb-86ce-edf0880ccc73.png)

**To Reproduce**
1. Set Server.xml as default

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
Ubuntu 20.04
 OvenMediaEngine Version: 0.12
clean install
 Branch: master

**Comment by bchah** [comment]
I will add to say that I have been struggling with connection reliability issues too. A few weeks ago there were some commits around FFMpeg and Intel HD Drivers, since these commits the master branch has had a similar issue to the one you describe. In my instance the player just gets stuck in a loading state and you need to reload a couple of times. It's inconsistent and I couldn't find any errors so I haven't reported it yet myself. Thanks for starting the thread though!

**Comment by getroot** [comment]
I need the following specific information to reproduce this.

- You said "very difficult to connect to the stream in all protocols". Does that happen with encoders like RTMP Push?
- Or does the problem occur only on the output side like WebRTC, HLS, DASH Streaming?
- Does "unstable" mean video stuttering? Or does it mean that the connection to the stream is not established or is disconnected?

**Comment by diegocisneros1967** [comment]
occur only on the output side like WebRTC, HLS, DASH Streaming.
"unstable" mean video stuttering, connection to the stream is not established, and is disconnected after a few minuts or seconds, I have observed all these cases

**Comment by basisbit** [comment]
I see similar behavior for HLS, DASH and LL-DASH over a typical long-distance internet connection.
This is what the dash reference player shows as buffer sizes for LL-DASH from OME.
![image](https://user-images.githubusercontent.com/10870269/119284729-b8d7a080-bc40-11eb-81d4-f548c8a8d29d.png)

When using another LL-DASH streaming service form the same datacenter over the same distance, the buffer size is mostly a flat line, occasionally going up to a second up or down.

**Comment by getroot** [comment]
I tested OME for hours today using 0.12.0. But I haven't been able to find any issues with streaming quality. ?transport=tcp is also working properly. Can you give me more hints to reproduce the problem?

The site below is our demo server running on an old device (4 core) and a network limited to 10 Mbps. And today we updated the server on this site to the latest version 0.12.0. Could you please check the quality of streaming on the sites below?

http://demo.ovenplayer.com/ome_demo.html

**Comment by diegocisneros1967** [comment]
And what do you think about the screenshot of thedirectory where is OME  and the crash_20210522dump.docx? 
What did you find there?

**Comment by dimiden** [comment]
@diegocisneros1967 
1. A strange (unreadable) file name was created because file logging was attempted after the ```LogWrite``` instance was released.
To elaborate further, ```Initialize()``` has been invoked since ```LogWrite``` instance was destroyed, and the already released ```_log_path``` was referenced, resulting in a file with an invalid name.
This is a symptom that occurs after the crash, so you can ignore it. (We have confirmed that it will be reproduced when OME is shut down by pressing <kbd>ctrl</kbd>+<kbd>c</kbd> several times, and we have a plan to modify it soon.)
2. The crash log can be analyzed only when you upload OvenMediaEngine binary file that is not "striped" - which contains debug symbol information. If OME was built from source, incorrect call-stack may be obtained because RVA may vary depending on the compiled environment.
So, please upload the binary you tested, If possible, it is best to reproduce it in a built environment in debug mode. (just build with ```make -j $(nproc)``` command)

**Comment by diegocisneros1967** [comment]
getroot

>>Could you please check the quality of streaming on the sites below? 
>>http://demo.ovenplayer.com/ome_demo.html

The same behavior. 
But with ?transport=tcp can connect but the image stops frequently. The sound is interrupted, and after few minutes disconects

![Ome2](https://user-images.githubusercontent.com/84642882/119333261-55765e80-bc92-11eb-91a3-7e1a47614840.jpg)
![Ome1](https://user-images.githubusercontent.com/84642882/119333305-6030f380-bc92-11eb-9ecf-9dbaab74e926.jpg)
![OME3](https://user-images.githubusercontent.com/84642882/119333332-6921c500-bc92-11eb-8674-afef922a0acc.jpg)
![OME4](https://user-images.githubusercontent.com/84642882/119333355-717a0000-bc92-11eb-8dc2-026be0ed08f1.jpg)

**Comment by getroot** [comment]
@diegocisneros1967 
The dev2 server works fine in my environment. This may be a problem with a slow network or an encoder configuration problem.
Could you please upload your encoder information and configuration information so that I can reproduce your problem the same?

**Comment by getroot** [comment]
@bchah Could you please check if the same problem as @diegocisneros1967 occurs on the dev2 server?

**Comment by diegocisneros1967** [comment]
getroot 
With previous versions on the same server, the problem is not observed . There is now a version from May 18 and works fine. 
It seems important the remark makes bchah  "A few weeks ago there were some commits around FFMpeg and Intel HD Drivers, since these commits the master branch has had a similar issue to the one you describe ".

>>Could you please upload your encoder information and configuration
Yes today i will.

Thanks.

**Comment by getroot** [comment]
Yes I checked the comment too. To fix the problem, I have to reproduce the problem in my environment. But it doesn't reproduce in my environment, so I'm trying to imitate your environment.
When the problem reproduces, I revert to the previous commit, trying to find the commit that caused the problem to analyze the cause and fix it.
Are you sure the May 18th version of the master branch works fine? (Or is it the release branch?) There are no unusual commits after May 18th, which is very confusing.
Could you please tell me your encoder settings so I can reproduce the problem?

**Comment by diegocisneros1967** [comment]
getroot
I see now that i built it in May 12th.

**Comment by getroot** [comment]
I've tried several things all day today to reproduce unstable streaming at 0.12.0. In order to check whether it operates more sensitively to the network environment than 0.11.13, a test was conducted while simulating network speed, latency, and packet loss using a tool called SoftPerfect. It also created multiple streams and played multiple players at the same time. I also tested WebRTC/TCP and WebRTC/UDP at the same time. But I haven't been able to reproduce the problem. In my environment, it plays just as stable as 0.11.13.

![image](https://user-images.githubusercontent.com/17779085/119505747-3b2ea480-bda8-11eb-94f9-ac84af433ed9.png)

My environment: The server is Ubuntu 20.04.2 LTS and I used the default settings. The browser mainly uses chrome on Windows 10. OBS settings used for testing are as follows.

![image](https://user-images.githubusercontent.com/17779085/119506178-a37d8600-bda8-11eb-81ae-cf641d1b7294.png)

If anyone is having the same problem in 0.12.0, can you please let me know how to reproduce it? To solve the problem I have to reproduce this problem.

**Comment by diegocisneros1967** [comment]
@dimiden
>just build with make -j $(nproc
With the actual version (May 25th)

root@servideo:~/OvenMediaEngine/src# make -j $(nproc)
####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 4
   - GCC version             : 9.3.0
   - Build option            : DEBUG
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
   - Total Projects count    : 47

[1/3| 33%] Preparing directories...
[2/3| 66%] [executable] Linking OvenMediaEngine... => bin/DEBUG/OvenMediaEngine
/usr/bin/ld: intermediates/DEBUG/static/libtranscoder.a(transcoder_gpu.o): in function `TranscodeGPU::Initialze()':
/root/OvenMediaEngine/src/projects/transcoder/transcoder_gpu.cpp:24: undefined reference to `av_hwdevice_ctx_create(AVBufferRef**, 
AVHWDeviceType, char const*, AVDictionary*, int)'
/usr/bin/ld: /root/OvenMediaEngine/src/projects/transcoder/transcoder_gpu.cpp:33: undefined reference to `av_hwdevice_get_hwframe_constraints(AVBufferRef*, void const*)'
/usr/bin/ld: intermediates/DEBUG/static/libtranscoder.a(transcoder_gpu.o): in function `TranscodeGPU::Uninitialize()':
/root/OvenMediaEngine/src/projects/transcoder/transcoder_gpu.cpp:47: undefined reference to `av_buffer_unref(AVBufferRef**)'
collect2: error: ld returned 1 exit status
make: *** [core/build_executable.mk:9: bin/DEBUG/OvenMediaEngine] Error 1

I hope this helps
Thanks.

**Comment by dimiden** [comment]
@diegocisneros1967
@kwonkeukhan  seems to have modified it recently (4ff7fdf112ba508d5720654bdee7cd0d6936124d, a04f8ef50b25949ef680b4ce3c84cacc9b6040a9). Could you do it again? (I'm sorry to bother you)

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
