### ISSUE TITLE
Trouble Building

### ISSUE THREAD

**Issue by Haunterz** [AirenSoft/OvenMediaEngine#38]
I've run out of ideas on how to fix this, and was wondering if I could get some help. Thanks!

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

![sB1THYR](https://user-images.githubusercontent.com/53807115/62511956-d2d59400-b7ca-11e9-9e76-437b0b6cb196.png)

EDIT: I should point out that i'm attempting to run this on a Raspberry Pi 3 Model B. I suspect that's the real problem here.

**Comment by JehoenHan** [comment]
Since we don't have a Raspberry Pi, it's very difficult to analyze this problem.
Can you install Docker on the Raspberry Pi? We recently created Docker Image. I hope this helps you.

https://hub.docker.com/r/airensoft/ovenmediaengine

[Command Example]
docker run -d -e OME_VIDEO_BITRATE=2000000 -e OME_VIDEO_WIDTH=1280 -e OME_VIDEO_HEIGHT=720 -p 1935:1935 -p 3333:3333 -p 80:80 -p 9000:9000/udp -p 10000-10005:10000-10005/udp airensoft/ovenmediaengine

And the Dockerfile may be helpful for you. Because the Dockerfile is based on alpine linux. 
https://github.com/AirenSoft/OvenMediaEngine/blob/temp/alpine/Dockerfile

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
