### ISSUE TITLE
HLS on edge returns an empty body and a 202 status code

### ISSUE THREAD

**Issue by 90minutes** [AirenSoft/OvenMediaEngine#384]
Currently the first users to request the m3u8 playlist get an empty body and a 202 status code while the media engine transcodes OVT into HLS, and takes ~15-20s, which means that players would return invalid manifest errors for the first few users.

**Describe the solution you'd like**
Wouldn't it be better to not respond to the request till the first segment becomes available? You can then respond with the first segment and the players would fetch the manifest again to retrieve the rest of the segments after they get transcoded.

![image](https://user-images.githubusercontent.com/42193957/119743442-cb8ce800-be81-11eb-9a00-c3e78bce6e88.png)

**Comment by getroot** [comment]
In our previous experience, blocking did not provide a valid experience because each player had a different timeout. Rather, this made OME's resource intensive, resulting in a worse experience.
So we return 202 and the player that supports 202 (OvenPlayer) keeps trying to reconnect, and the player who does not support 202 will fail to connect as before.
Rather, we aim to make OME run as an http reverse proxy when running as HLS Edge. Now, even when OME Edge operates as HLS, it receives streams through ovt and packetizes them again at the edge. This has many drawbacks in a number of ways, including the reasons you reported. I think the current OVT is actually for WebRTC.

**Comment by 90minutes** [comment]
Understandable! Thanks for the amazing project and the prompt replies.
