### ISSUE TITLE
Documentation of Depends

### ISSUE THREAD

**Issue by genofire** [AirenSoft/OvenMediaEngine#390]
**Is your feature request related to a problem? Please describe.**
For Packaging and Deploying it is really interesting, which packages are really needed.

**Describe the solution you'd like**
documentate the [depends/prerequisites](https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/prerequisites.sh) after:
- **required** on deploy
- **optional** on deploy
- just for build (**makedepends**)

**Comment by getroot** [comment]
That's a good idea. If someone doesn't need live transcoding function when using OME, there is no need to install codec library.

But we can't start this because we have a lot of high-priority tasks left. If you contribute a PR to the manual repository, we will be very happy to review it. https://github.com/AirenSoft/OvenMediaEngineDocs

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
