### ISSUE TITLE
SRT URLs for hardware encoders

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#400]
I am streaming to OME from OBS using SRT successfully. We have SignedPolicy enabled and working too. 

I don't currently have a hardware SRT encoder to test with, but I wondered if SignedPolicy URLs would work with a hardware encoder like the [Videon EdgeCaster](https://videonlabs.com/edgecaster/), which looks like it has a pretty rigid Server URL implementation with the port field separated?

![mceclip14](https://user-images.githubusercontent.com/67900507/120474300-f2767d00-c39f-11eb-8656-761975b5afdb.png)

**Comment by getroot** [comment]
SRT is basically a structure in which stream and port are mapped 1:1 like MPEGTS/UDP. To overcome this limitation, SRT has supported streamid since version 1.3.3, and streamid provides a method to transmit multiple SRT streams in a single UDP port.

OME has specified a specification to put a whole URL in the streamid to provide functions such as virtual host and SignedPolicy even in SRT. If some hardware encoder does not support SRT streamid, it cannot be used with OME. (I know most SRT encoders these days support it.)

https://github.com/Haivision/srt/blob/master/docs/features/access-control.md

**Comment by llspalex** [comment]
Ok, thanks. Looks like some hardware encoders will need to catch up with the spec!
