### ISSUE TITLE
how to relay webrtc?

### ISSUE THREAD

**Issue by itsko** [AirenSoft/OvenMediaEngine#404]
I want to test webrtc broadcasting.

I tried to follow [**clustering doc**,](https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering) to make it look like the image below, but it doesn't work for webrtc.
<img width="1584" alt="01_OvenMediaEngine_210512" src="https://github.com/AirenSoft/OvenMediaEngine/raw/master/dist/01_OvenMediaEngine_210512.png">
only hls relay is successful, but webrtc is failing.

OK : OBS(rtmp)->origin-> vlc hls (http://orgin/app/test/playlist.m3u8)
OK : OBS(rtmp)->origin->ovt->edge -> vlc hls (http://edge/app/test/playlist.m3u8)
OK : OBS(rtmp)->origin-> demo webrtc (ws://origin:3333/app/test)
Fail : OBS(rtmp)->origin->ovt->edge -> demo webrtc (ws://edge:3333/app/test)

is there any sample conf (origin/edge) to enable webrtc relay?

**Comment by getroot** [comment]
Please upload your Server.xml for origin and edge and ovenmediaengine.log files.

And example config files are here.
https://github.com/AirenSoft/OvenMediaEngine/tree/master/misc/conf_examples

**Comment by basisbit** [comment]
Could the samples be extended to support encrypted WebRTC playback? Playback without encryption does not work in most use cases (because webbrowsers require TLS and don't allow mixed content in most cases) and getting WebRTC publisher to work with encrypted signalling and so on is quite a pain because of lack of error messages from the client and the server, unless everything is correctly configured... Thanks in advance!

**Comment by getroot** [comment]
@basisbit 
What you want is to set the signaling port of WebRTC as the TLS port, configure the certificate and domain like HLS, and use the address starting with wss://domain as the playback URL.

https://airensoft.gitbook.io/ovenmediaengine/streaming/tls-encryption

Extending the sample would be difficult because I can't provide a certificate, is there a good way?

**Comment by basisbit** [comment]
I tried what you mentioned and the OvenPlayer just does nothing when I try to have it play the stream. No warning/error entries in the edge server log and nothing in the browser console. Thus, a minimal working sample config would be nice. For the TLS certificate path, just specify it so that it works for a example.org domain using Let's Encrypt and so on.

**Comment by getroot** [comment]
@basisbit 
Your setup is a good edge sample configuration. And, unfortunately, I have never experienced Let's Encrypt. This would be nice if you or someone else could post a PR.

If neither the server nor the browser log showed anything, maybe the TLS port was entered incorrectly? Is wss://domain:3334/app/stream correct? How does it appear in the network tab of chrome? Does your firewall allow 3334?

**Comment by basisbit** [comment]
Small update from my side: I finally got a sample setup working, including a WebRTC player which is only 45KB in size (based on OvenPlayer code). I'll test it this weekend at a ~30k attendees animation fan convention (free to attend online event) and once I have the results, will prepare a pull request for the documentation repository. There is another event one week later, after that I should be able to find some free time to write a OME usage story as requested.

**Comment by basisbit** [comment]
I sent you an email with details about the event and the used setup.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
