### ISSUE TITLE
Documentation and sample codes

### ISSUE THREAD

**Issue by bakamaru** [AirenSoft/OvenMediaEngine#426]
Provide some use full docs and working sample codes repo for web rtc . There are so much missing parts :(

**Comment by getroot** [comment]
What topics of documentation and sample code do you think OME users need?

https://airensoft.gitbook.io/ovenmediaengine/

You can publicize the documentation and sample code in the Repository below at any time.

https://github.com/AirenSoft/OvenMediaEngineDocs

**Comment by getroot** [comment]
Since OvenMediaEngine is a streaming server, there can be no such thing as a "sample app".

We provide an example of using the player at http://demo.ovenplayer.com/. And we provide a demo page where you can try pre-installed streaming servers. http://demo.ovenplayer.com/ome_demo.html

Thanks for your suggestion.
