### ISSUE TITLE
Current bits in/out in statistics API

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#435]
Hi,
Could you add current bits in/out to this API endpoint?
https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/statistics/current

**Comment by basisbit** [comment]
The API endpoint already has total bits in / out, and you can poll the API for example every 15 seconds and then calculate the difference. Also, if the number is lower than the previous value, you know that the counter has either overflown or the server was restarted. This is also how typical network monitoring solutions work.

Otherwise the question would be of what time frame you want the average and so on. With the current solution, you can decide that for yourself.

**Comment by fcqpl** [comment]
Hehe, I didn't think about this way. I'll implement this in my code.

**Comment by getroot** [comment]
@basisbit You are truly a media/network expert. Thank you.
