### ISSUE TITLE
Auto fallback to TCP

### ISSUE THREAD

**Issue by MoZyo** [AirenSoft/OvenMediaEngine#473]
**Is your feature request related to a problem? Please describe.**
Got a lot of ICE errors. Some clients had to manually click the settings icon in the player and choose the TCP sources.

**Describe the solution you'd like**
I had to put extra sources in the player that have ?transport=tcp in them.
If UDP fails or lags... ICE and TURN goes on automatically.

**Describe alternatives you've considered**
Believe it or not I went on and purchased AMS because of this problem. I prefer OME and its concise guides and easier configuration.

**Additional context**
None I can think of.

**Comment by basisbit** [comment]
This is nothing that can be changed on the sever side for what you want, but instead is a client side task. You can implement this in your javascript player by listening for playback errors and for example after two playback failure, auto-fallback to WebRTC over TCP, and if that fails twice, fallback to HLS.
If you are using OvenPlayer, then this already is supported using the playlist feature and having it just go play the next entry on error.

**Comment by MoZyo** [comment]
@basisbit Yes, that is nice to know. I deployed and was streaming to a few hundred people 15 hrs ago with this player source config (See picture below).
I just think it would confuse viewers as to what to choose. Maybe it would be better to have a ?transport=tcp backup hidden behind the main source.

![image](https://user-images.githubusercontent.com/65864218/129488220-a9791c5e-4926-4330-937a-a0250b5089a0.png)

**Comment by basisbit** [comment]
Then https://github.com/AirenSoft/OvenPlayer/issues is the place for such an issue.

**Comment by basisbit** [comment]
then https://github.com/AirenSoft/OvenPlayer/issues is the right place for such an issue

**Comment by MoZyo** [comment]
> 
> 
> then https://github.com/AirenSoft/OvenPlayer/issues is the right place for such an issue. PS: I have been streaming to ~ 20k viewers all of this weekend (and bunch of times previously the past months) with the above mentioned way of auto-fallback on playback problems / stuttering. I also store in the browser's localStorage which type they had manually selected previously / worked well for them and then reuse that for the next time they start a video.

That's nice! What specs do you have to serve that number? Are you running in a cluster? Mine's having a hard time serving 220 concurrent viewers.

**Comment by basisbit** [comment]
that uses a mix of hourly billed dedicated bare metal servers and virtual cloud servers in USA, Germany and Singapore. In total for this weekend event 16 servers and roughly a budget of 100€. RAM and HDD don't really matter from my experience, and CPU as well as Network requirements can be calculated quite easily. WebRTC over UDP or TCP requires roughly twice as much CPU time as serving HLS.
Very important is to either not do video transcoding or only do it on your origin server, but not on the edge servers, so that you can use edge servers that are very cheap (but still have to choose servers with very good network peerings and which have consistently enough CPU power for your amount of users).

From my experience, a lot of server providers oversubscribe the CPU resources too much, or have noisy neighbor problems on the network uplink or similar issues. Thus, choice of data center provider is very important if you want to stream to more than just a few hundred users concurrently. Asking the server providers usually doesn't give a helpful response because they (support agents) either don't know what they are talking about, or they'll just lie (especially common for the smaller DC providers) or just not answer anything helpful because they don't want to tell. So the best is to just do testing by yourself, at different times of the week and collect data.

**Comment by MoZyo** [comment]
Thank you very much for those tips. I was actually reading about clustering and just trying to grasp it for the past couple of days.

I've been on htop nonstop... I only have a VPS (8x vCore, 16GB RAM, 2Gbps) doing it all except for the LEMP stack which is a Bare Metal (shoud've been the other way around?). And yes, it really has to be CPU oriented.
For now, I don't have a problem on transfers because I only serve 480p 556kbps at max setting and 2Gbps has got it covered... but I do a lot of transcoding even though I only use WebRTC because the latency is all that matters.

I know it's out of topic but I have doubts with my OutputProfiles. Could you check if I have set them up to waste a bit of resources?

Also, the Timeout isn't explained in the guide, there's one for WebRTC Publishing and another for Providers. I do want to have a 30min timeout for each idle viewer.

[OutputProfiles.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6988930/OutputProfiles.txt)

**Comment by basisbit** [comment]
- the OVH VPS Elite only uses spare leftover resources, so usable CPU time varies a lot over time, and especially the upload bandwidth is low priority, so I'd personally not expect that to reliably do more than 300Mb/s outbound.
- virtual machines can be used, but then you'll have to test and hope that enough resources will be available for your usage. Alternatively to dedicated bare metal servers, better use virtual machines with dedicated CPU threads, for example something like OVH Public Cloud Compute instances for transcoding.
- your output profiles do transcode video to vp8 and h264. I'd suggest only using h264 if you only have default end-users.
- order of the Encodes entries is important - it seems like you spend the CPU time for transcoding but then deliver the original video data in most cases.
- If you are using current master branch and don't care about video quality, change this from `faster` to `ultrafast`: 

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/transcoder/codec/encoder/encoder_avc.cpp#L77

**Comment by getroot** [comment]
With the settings below, the publisher will use the top of the available tracks. If Audio is input in AAC, it cannot be used in WebRTC, so use OPUS below.

```
<Encodes>
	<Audio>
		<Bypass>true</Bypass>
	</Audio>
	<Video>
		<Bypass>true</Bypass>
	</Video>
	<Audio>
		<Codec>opus</Codec>
		<Bitrate>96000</Bitrate>
		<Samplerate>48000</Samplerate>
		<Channel>2</Channel>
	</Audio>
	<Video>
		<Codec>vp8</Codec>
		<Bitrate>4448000</Bitrate>
		<Framerate>30</Framerate>
		<Width>854</Width>
		<Height>480</Height>
	</Video>
</Encodes>
```


If it is set as below, WebRTC will select only h264 in most cases, so it is recommended to remove VP8. This is because it only wastes CPU resources.

```
<Video>
	<Codec>h264</Codec>
	<Bitrate>640000</Bitrate>
	<Framerate>24</Framerate>
	<Width>426</Width>
	<Height>240</Height>
</Video>
<Video>
	<Codec>vp8</Codec>
	<Bitrate>640000</Bitrate>
	<Framerate>24</Framerate>
	<Width>426</Width>
	<Height>240</Height>
</Video>
```
