### ISSUE TITLE
Set RTSPpull timeout

### ISSUE THREAD

**Issue by Classsic** [AirenSoft/OvenMediaEngine#485]
After setup RTSPpull provider, some rtsp device get more than usual (up to 30 seconds) to connect.
Is possible set larger  timeout for rtsp connections?
Thanks.

**Comment by getroot** [comment]
If it takes more than 30 seconds, it would be better to try to reduce the time first. Wouldn't it be helpful to reduce the key frame interval of the RTSP source?

To change the timeout of 30 seconds, you need to modify the source code.

https://github.com/AirenSoft/OvenMediaEngine/blob/fac803e27d95532e7d0bca24754456694371b334/src/projects/providers/rtspc/rtspc_stream.cpp#L227

**Comment by getroot** [comment]
I'm revisiting old issues.
If the TCP connection takes more than 30 seconds as I answered in the first place, then I think there is a huge problem with the network. Nevertheless, in order to set the timeout to more than 30 seconds, there is no other choice but to modify the source code. (I still don't understand the situation where the TCP connection takes more than 3 seconds.)
If you would like to discuss this issue further, please do not hesitate to reopen this issue.
