### ISSUE TITLE
WebRTC publisher audio sync issue in Safari 14+

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#521]
This is an ongoing issue with audio/video sync in Safari since v14 (iOS 14 / macOS Big Sur).

If you use a WebRTC publisher and play back with OvenPlayer (the standard use case for OME), the audio is noticeably delayed behind the video. Testing on an older iPhone 6 with iOS 12, the sync is fine so this is a regression from Safari 14 (or possibly 13 - but all devices with Safari 13 now run 14 so it is not possible to test).

I reported this issue to the OvenPlayer project originally but not much has come of it:
https://github.com/AirenSoft/OvenPlayer/issues/179

Can anybody here reproduce this? An easy test is to open a stream in Safari and Chrome at the same time, and you will easily perceive the lag in Safari. This impacts all iOS devices since Safari is the only browser available on iOS.

Here is a video demonstrating the difference between Safari and Chrome playback. It is reproducible on all versions of OME for me:

https://user-images.githubusercontent.com/33604674/134745461-5413c8b3-5be8-4443-a25c-6447c5ab889f.mp4

**Comment by getroot** [comment]
Thanks for reporting.  This issue I've been working on since last week.

**Comment by bchah** [comment]
@getroot I tested again on your latest commit https://github.com/AirenSoft/OvenMediaEngine/commit/d84662f5c62514a9afd4768e23238c06b94b870b

The sync is noticeably improved in Safari on macOS (but still a little behind Chrome which has perfect sync).
It does not seem to change the situation on iOS (the iPad at the bottom is the most delayed)

I hope this information is useful for you! Thank you for your hard work on this so far.

Updated example: 

https://user-images.githubusercontent.com/33604674/134955420-543ff12a-8974-4217-9a12-83467a470c1f.mp4

**Comment by getroot** [comment]
Have you tested with JitterBuffer added to WebRTC? I'm surprised you're just looking at the code and doing it even though I haven't opened it yet.

I'm still fighting against lip sync. This JitterBuffer is one of my experiments. Chrome, Firefox, and Safari all behave differently, so I'm very confused. And it's very hard for me because there is no documentation that explains it in detail.

Anyway I have to finish this this week. good luck to me!

**Comment by bchah** [comment]
With `<JitterBuffer>` set to true in WebRTC publisher, the sync is now **perfect** on macOS Safari, but the same on iOS. I don't know if this is just my perception or not, but it seems solid on macOS now 👍 

I have good faith in you @getroot !! Anything I can do to help, I am happy to contribute.

🥇

**Comment by basisbit** [comment]
@bchah does lowering WebRTC player-side jitter buffer help with this? I got reports months ago about a similar problem, and got a "good enough" solution by offering users to switch to a shorter jitterbuffer playback option using `webrtcConfig: {playoutDelayHint: 0.3}`, vs a by (default in my code for better stability) much longer playoutDelayHint.

**Comment by HighK** [comment]
From version 0.8 to 0.12.4 of Oven Media Engine, we witnessed a perceived delay of 0.1~0.2 seconds in the video in WebRTC.

enabled the <JitterBuffer> option while testing the OME to which the commit was applied, and we felt that there was an improvement in A-V Sync.

We were running the OvenMedia Engine using an AMD EPYC 7702P CPU. I have only tested Chrome as a web browser.

We plan to test again in worse network conditions.

**Comment by bchah** [comment]
Thank you both for the input!

With or without `<JitterBuffer>` enabled server-side, using the `playoutDelayHint` property of the player webrtcConfig only seems to add latency if anything (therefore stability), but I can't see any measurable improvement in sync. In fact I may not even be using it correctly as I tried setting it to wild values like 5, -100, string values etc. and didn't see any difference 🤷‍♂️ 

@basisbit I must be doing something wrong here? Perhaps another coffee, then another test 😅 

With `<JitterBuffer>` enabled server-side, I do notice an improvement in sync as mentioned by @HighK but at the cost of additional latency. While it is an improvement, the sync is still noticeably off when compared to playback in Chrome.

None of the improvement seems to show yet on iOS. Could a solution maybe be somewhere at the player level? Originally I was looking for ways to offset the video to match the audio, but gave up due to lack of skill.

**Comment by getroot** [comment]
I didn't sleep today to do this. I'm looking for the cause by doing various experiments. In my experiments so far (with uncommitted code) chrome and firefox work fine, but iOS keeps running away from me.

**Comment by getroot** [comment]
I've been doing a lot of research on this issue in the last few days.
The problem with Safari is that when safari renders Audio(OPUS) and Video for the first time, it renders audio with delay. It's a delay on the rendering side, so perhaps Safari doesn't correct the A/V Sync any more when it receives an RTCP SR because it considers the state to be correct. (If I intentionally send the NTP Timestamp of the RTCP SR wrong by 400ms, Safari corrects it.)

I don't know when this problem started. I haven't tested it yet to see if this problem can be reproduced in older versions of Safari.
(JitterBuffer is an experimental feature created during testing. It still lacks exception handling such as handling when the buffer overflows.)

When I first found out about this, I naturally assumed there was something wrong with the OvenMediaEngine, so I started looking into everything from opus codecs to aac decoding, resampling, rtp transfer, rtcp sr, etc. But I haven't been able to pinpoint the cause of this problem yet.

And today I tested A/V Sync with "Safari on iPhone" and "Chrome on PC" at https://appr.tc/. And I have observed lag on iPhone even on p2p connections.

I'm still not sure about this issue. Can someone please do this test with me? I would like to know if this problem is reproduced in other WebRTC related services like appr.tc, Janus, AntMedia etc. Or if someone already knows about this, please do share.

I think that sometimes this problem may occur again as the browser and player are updated. This is a very fatal problem for commercial services. So I'm thinking about adding a command to the WebRTC signaling that can sync the A/V as much as the viewer wants (audio 100ms forward, backward). It seems that the worst case can be avoided by providing a button on the player. What do you think about this?

**Comment by bchah** [comment]
Hi @getroot thank you for your continued efforts here.

I tested with appr.tc and the sync worked well for me between Safari 15 on macOS Big Sur (Mac Pro) and Safari 15 on iOS (iPhone 12). I also tried whereby.com and it is working well in terms of sync (they have some UI issues though!). Does that one work for you?

I agree that a solution at the player level would be best. I am not sure if this is possible in OvenPlayer alone, but it would be very useful to have a player method like `setVideoDelay(ms)`. At the basic level, we could detect a Safari browser and apply a standard delay like 300ms. Or we could use it in a more advanced way to provide our users with a UI to let them set the delay themselves. Do you think this is possible at the OvenPlayer level?

**Comment by getroot** [comment]
Even in my tests there were no issues between Safari. But sending from chrome causes delay in safari's audio. I just tested it with Chrome on PC and Safari on iPhone via Janus, and observed audio delay in Safari. Chrome plays streams sent from Safari perfectly.

I think the A/V correction function is provided by OME. It will be added as a command to the WebRTC signaling server, and when any player sends that command, the server delays and transmits the audio. (To be precise, modify the NTP Timestamp of RTCP SR and send it) Of course, OvenPlayer will add a nice button to send that command to the server.

**Comment by getroot** [comment]
@bchah 
We found something strange in Safari and added it to our latest OvenPlayer code.  We have applied the latest player to http://demo.ovenplayer.com.  I'm still not sure if this has fixed the problem (because it's a very strange phenomenon...). Could you please test it again with the latest player?

**Comment by getroot** [comment]
@bchah 
We added a strange code for safari to OvenPlayer 0.10.8. AudioContext is only initialized, and AudioContext is not actually used. However, that alone solves the audio delay problem in Safari. I worked all night this week for three days to analyze OvenMediaEngine's codes to solve this problem. I started to hate Safari.

Now, the Lip-sync problem has been completely solved in the iOS Safari we have. Could you please check if the problem has been solved in your environment as well?

**Comment by bchah** [comment]
@getroot SUCCESS 😁😁😁

"Thank you" is not enough to celebrate your hard efforts to get this solved.

This is a significant improvement and 1 billion users will benefit, even though Safari is becoming the new Internet Explorer.

It was so satisfying to finally see the phone and computer playing in sync together. Today is a good day 👍

**Comment by basisbit** [comment]
You all rock! Thank you for all this work and dedication!

**Comment by getroot** [comment]
I also sincerely appreciate your contributions. You guys are obviously doing a great job in advancing OvenMediaEngine.
@bchah @basisbit
