### ISSUE TITLE
Limit providers to ip or domain

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [AirenSoft/OvenMediaEngine#526]
**Is your feature request related to a problem? Please describe.**
I want to use this wonderful software, but I have one problem: Currently (with srt-live) all my providers need to be in a VPN (so I can control, who can stream, because I do not have any other method of authorisation). Is it possible, to limit the providers to one ip or domain like applications, but allow thee viewers to access the publishers?

**Describe the solution you'd like**
Do it like nginx or how it is done in the applications, but for all or individual providers of one application.

**Describe alternatives you've considered**
Setting up another docker container just  for authorisation...

**Comment by dva-re** [comment]
I think you can try this https://airensoft.gitbook.io/ovenmediaengine/access-control/signedpolicy

Enable it only for the required provider and generate a link valid for 100 years (for example, because url_expire always required) but only for a specific IP address.

**Comment by TheCataliasTNT2k** [comment]
Would be a solution, but has some drawbacks:
First only one can stream with this. Second you have to update the config each time you want to enable or disable a signed policy. I think, this is not meant for such things.(And I do not know, for what this is used either, because this is not very dynamically...)

**Comment by getroot** [comment]
@TheCataliasTNT2k 
SignedPolicy or AdmissionWebhook is exactly what you want. You can use multiple streams by issuing multiple URLs to the SignedPolicy, and you don't even need to turn SignedPolicy on and off. When creating a URL, you can limit it to IP by putting the client IP in the policy, and shorten the expired time so that the URL can be automatically destroyed. AdmissionWebhook can be more scalable because it always asks the server you set up when a user wants to send or play a stream. Please take a closer look at the documentation. (If you don't understand, take a look at SignedURL in AWS Cloudfront, it's a very similar feature.)

https://airensoft.gitbook.io/ovenmediaengine/access-control

**Comment by TheCataliasTNT2k** [comment]
Ok, AdmissionWebhook would be a solution for this, if you are able to code one yourself. But you would need an additional container or something.
So you can not do it with OME alone.
Additionally, I tried to watch a teststream with your testplayer, no matter which protocol I used, I got no connection (publishing was no problem though and was logged correctly, but viewing was not even logged), so I do not use it at the moment.

**Comment by getroot** [comment]
@TheCataliasTNT2k 
I don't understand what you want. SingedPolicy meets all your requirements in the first question you asked. You can set the following settings so that the provider can transmit only to the URL you issued, and you can restrict the IP of the client in the policy in the URL. And if you set all publishers to disable as shown below, all players can play without restrictions as you like. You can easily create URLs for providers with the script command we provide. https://airensoft.gitbook.io/ovenmediaengine/access-control/signedpolicy#make-signedpolicy-url-with-a-script

```
<SignedPolicy>
  <PolicyQueryKeyName>policy</PolicyQueryKeyName>
  <SignatureQueryKeyName>signature</SignatureQueryKeyName>
  <SecretKey>aKq#1kj</SecretKey>

  <Enables>
    <Providers>srt</Providers>
    <Publishers></Publishers>
  </Enables>
</SignedPolicy>
```

What else do you want?


If there is no log on the server when you try to play, check your firewall or network settings carefully. If the problem persists, please take a screenshot of the player's log and post it as a new issue.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
