### ISSUE TITLE
WebRTC stat collecting

### ISSUE THREAD

**Issue by Zinelaabidine** [AirenSoft/OvenMediaEngine#550]
Are WebRTC stats like packet loss and RTT provided in the API REST?

**Comment by getroot** [comment]
It is information collected from individual sessions, and OME does not provide individual session information in its API.  Please refer to the manual for details.  Because sometimes there are thousands or more.  The code is collecting that information, so you can write the relevant code if you want.

**Comment by Zinelaabidine** [comment]
Thanks.
is it within **rtp_rtcp** module?  could you plz point me to the code so I can add customize code.

**Comment by getroot** [comment]
You can start here

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/publishers/webrtc/rtc_session.cpp#L315

**Comment by Zinelaabidine** [comment]
Thanks, I will start from there
