### ISSUE TITLE
WebRTC Datachannel not connecting

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#561]
I've implemented a simple service to obtain stream names from the OME api to provide a conference feature. However without a websocket server commands are required to be sent over a data channel
```
pc.createDataChannel(..)
```

This doesn't seem to be enabled. It's stuck in a readyState of "connecting". If I need custom commands to peers do I need to try the websocket method ?

**Comment by getroot** [comment]
OvenMediaEngine doesn't support WebRTC Data Channel.

**Comment by danrossi** [comment]
OK. The post proxy service to obtain streams is useless then, I had that working. Have to go back to the websocket idea for conferencing to message commands to peers.

**Comment by getroot** [comment]
There is something I don't really understand.

OvenMediaEngine is a solution for hundreds of thousands of high-volume, low-latency live broadcasts. Therefore, it basically considers the cluster(Origin-Edges) structure.

However, this is not a good structure for two-way communication. This is because each Session attached to multiple Edges must be designed like a game server to communicate with each other.

Rather, it is an SFU like Janus that is advantageous for two-way communication. This is specific to conference calls. Unlike OME, the concept of Room is installed by default.

Why would you use OME for conference calls instead of Janus? If I understand it, I might invest more in it.

**Comment by danrossi** [comment]
I'm just trying to add options for conferencing like I have for the other server options. I have Ant Media Server, Wowza Media Server and Millicast working so far but only Ant Media have room websocket calls, the others is custom websockets, to initiate subscribing to participant streams. And the master can send commands to peers to show a participant as featured which scales to 80%. Like how zoom works. 

I have manual recording calls working for Ant Media Server and trying to do the same for OME via a rest service or websocket service calling the OME api right now. For the single OME publisher it can use a custom rest service to tell to start recording.  I'm trying to figure out how to do the same for Wowza right now. 

https://electroteque.org/plugins/videojs/rtcstreaming/demos/#ovenmedia

With the Ant Media option, the WebGL camera merger published stream can be selected to be recorded and initiate record via the record button. 

https://electroteque.org/plugins/videojs/rtcstreaming/demos/antmedia-conference-master/

With client side peering the client takes on the bandwidth sending also. I believe this is how Kinesis works. https://electroteque.org/plugins/videojs/rtcstreaming/demos/#aws
