### ISSUE TITLE
How to externally edit server config in Docker

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#563]
I have Docker configured as WSL but there is still no way to access the file system. Every time I try and edit the config file, if the xml node is in the wrong place the entire container won't boot. And takes hours to set the test server back up. I don't like Docker but OME failed to compile every time I tried. 

I just tried to turn on recording provider to test api recording options and the container failed to boot again. 

```
<FILE>
		<RootPath>/mnt/shared_volumes</RootPath>
		<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
		<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
	</FILE>
```

Is there a way to load external configs ?

**Comment by getroot** [comment]
Readme.md has the following guide: Search the Docker community for more details.

```
docker run -d \
-p 1935:1935 \
-p 3333:3333 \
-p 3478:3478 \
-p 8080:8080 \
-p 9000:9000 \
-p 9999:9999/udp\
-p 4000-4005:4000-4005/udp \
-p 10006-10010:10006-10010/udp \
-v ome-origin-conf:/opt/ovenmediaengine/bin/origin_conf \
-v ome-edge-conf:/opt/ovenmediaengine/bin/edge_conf \
--name ovenmediaengine \
airensoft/ovenmediaengine:latest

The configuration files are now accessible under /var/lib/docker/volumes/<volume_name>/_data.
Following the above example, you will find them under /var/lib/docker/volumes/ome-origin-conf/_data and /var/lib/docker/volumes/ome-edge-conf/_data.

If you want to put them in a different location, the easiest way is to create a link:

ln -s /var/lib/docker/volumes/ome-origin-conf/_data/ /my/new/path/to/ome-origin-conf \
&& ln -s /var/lib/docker/volumes/ome-edge-conf/_data/ /my/new/path/to/ome-edge-conf
```

**Comment by danrossi** [comment]
I'm using Docker desktop on Windows not Linux.

**Comment by danrossi** [comment]
I'm confused why the whole instance fails to boot on config errors. Even the xml node in the wrong place causes a crash. Like what happened. So can't be edited.

**Comment by getroot** [comment]
Volume or bind mount on Windows docker desktop is not an issue that OvenMediaEngine can handle. It would be good to find out about this in the docker community.

**Comment by danrossi** [comment]
OK. I'll see how to load external configs for Windows. I am back onto Wowza dev now to be honest. I'll delete the broken container and set back up again. But for some reason it will not boot if I put that file recorder section in the config. The container also crashes and stops if I had run recorder api calls without the file provider configured.

**Comment by danrossi** [comment]
Is there a way to stop the instance crashing on config errors ? I still find it hard to put configs in the right place and then it crashes and have to set it back up again. 

Ie putting the api token under the wrong host node. 

https://airensoft.gitbook.io/ovenmediaengine/rest-api

**Comment by getroot** [comment]
Hmm... it's probably not a crash. The OvenMediaEngine process is not running because the config is incorrect. Docker instances are terminated when the main process exits. Because the instance has no reason to keep running.

In the Dockerfile of OvenMediaEngine, CMD is defined as below.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/Dockerfile

CMD ["/opt/ovenmediaengine/bin/OvenMediaEngine", "-c", "origin_conf"]

You can override the default CMD by putting the command you want at the end of the docker run command.

docker run -it airensoft/ovenmediaenigne:latest /bin/bash

After running bash like this, go inside the instance and try it. OvenMediaEngine is located in /opt/ovenmediaengine/bin .

If you search for more details, you can get many methods as below.

https://phoenixnap.com/kb/docker-run-override-entrypoint
