### ISSUE TITLE
/ Slash in App Name for RTMP

### ISSUE THREAD

**Issue by wizeyyy** [AirenSoft/OvenMediaEngine#576]
**Please describe the problem you are experiencing.**

Some video devices we use stream RTMP in the following format
`RTMP://<OvenMediaEngine IP>[:<RTMP Listen Port>/<App Name>/<Channel Name>/<Stream Name>`

Using Nginx this can be solved creating an application like  application live/0 
However we would like to move over from an Nginx environment to OvenMedia

**Please write how you would like the problem to be resolved.**

Allow / (forward slash) in in the App Name

**Comment by getroot** [comment]
I'll fix this.

**Comment by wizeyyy** [comment]
Thanks

**Comment by getroot** [comment]
I tried to handle this, but it is difficult to handle this type of exception for the time being because it conflicts with other modules in OME.

The form of HLS and DASH URLs in OME is as follows.

http://host:port/app/stream/playlist.m3u8
http://host:port/app/stream/manifest.mpd

A lot of changes are needed to handle this exception in the form of app/channel/stream only in RTMP. Also, if there are multiple slashes instead of one, many exceptions are bound to occur.

I recommend you use AdmissionWebhooks. AdmissionWebhooks instructs OME to use the new_url your server responds to. So your server can take app/channel/stream and respond with new_app/stream , which is an OME-compatible url.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
