### ISSUE TITLE
Audio bandwidth optimization

### ISSUE THREAD

**Issue by francescovitiello** [AirenSoft/OvenMediaEngine#58]
Good morning,

I am trying to create my home audio multiroom system. 
I have a PC used as streamer and  some Raspberry Pi connected to speakers used ad players.
The system works very well but i don't need a video while  I need  very low bandwidth consumption.

In order to reduce the bandwith consumption I tried to modify some parameters in Server.xml configuration file.

I reached 200kbps/connection by using a very low video bitrate and 25 frames/s.
About audio I set the samplerate from 48k to 44.1k but with these values there was no audio signal in the transmitted video. By using a lower samplerate the audio has appeared again but with a very low quality.

Please could you kindly provide me an help about the best configuration to use in order to have an acceptable audio quality(no music, only voice) and no video?

I also wrote to Jin-Seong Lee who kindly advised me to open this issue. 

Thanks for our efforts and support.

Regards,

**Comment by dimiden** [comment]
@francescovitiello 
I'm sorry for the late response because I'm concerned about stabilizing LL-DASH.

As Jin-Seong Lee answered by email, we do not currently have audio or video-only functionality, so I recommend you to try the following as a temporary method:

[Configuration]
```RTMP streaming tool``` - ```(1)``` - ```OvenMediaEngine``` - ```(2)``` - ```Player```

[Settings for RTMP streaming tool]
This is set to reduce bandwidth in above section ```(1)```, and this makes the video bandwidth very low.
1. Set the video bitrate to the lowest possible value.
2. Use a video that contains nothing. For example, use black images.
3. Set the video framerate to the lowest possible value. For example, set to 1.

[Setting for OME]
This is set to reduce bandwidth in above section ```(2)```, in which case no video is transmitted.
1. Delete ```<Video>``` element in ```<Encode>``` element of ```Server.xml```.

**Comment by getroot** [comment]
This issue will continue in #79 
Thank you for your suggestion.

**Comment by getroot** [comment]
We just committed code to the dev branch that allows audio only and video only streams in RTMP. (c69a795)

Please check post #79 for more details or to communicate.
