### ISSUE TITLE
Streaming SRT 

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#581]
**Describe the bug**

I'm experimenting with streaming via SRT instead of RTMP. Unfortunately, the image is pixelated and distorted:

I get the following message in the logs:

[2021-12-04 16:25:00.271] W [SPSRT-T9999:874] MPEGTS_DEPACKETIZER | mpegts_depacketizer.cpp:84   | An out-of-order packet was received.(PID : 256 Expected : 14, Received : 5

**To Reproduce**

I have audio and video encoding bypassed in the server.xml
My OBS settings are as follows:

Encoder: x264
Resolution: 1080p
Rate control: CBR
Bitrate: 10000 kpbs
Keyframe Interval: 1
CPU: Ultrafast
Profile: Baseline
Tune: Zerolatency
options: bframes=0 threads=8

**Logs**
[2021-12-04 16:25:00.271] W [SPSRT-T9999:874] MPEGTS_DEPACKETIZER | mpegts_depacketizer.cpp:84   | An out-of-order packet was received.(PID : 256 Expected : 14, Received : 5

**Server (please complete the following information):**
 - OS: ubuntu 18.04
 - OvenMediaEngine Version: 0.12.8

**Player (please complete the following information):**
 - Device: MacBook Pro M1
 - OS: 12.0.1
 - Browser Google Chrome
 - Version 96.0.4664.55

**Additional context**
The image quality degrades, specially after cuts. I'm testing with a very fast cut video, and the pixelation is specially noticeable after a cut.

**Comment by zygocact** [comment]
Hello.
I've been using SRT for a while successfully with WebRTC and sometimes HLS. I can not speak for DASH, and I don't recommend using it because it's very unstable right now.
Can you describe what the pixelation looks like? Is it just low quality compression, or is it artifacts, like shown here:
![vlcsnap-2020-05-28-14h41m34s850_proc_proc](https://user-images.githubusercontent.com/75622726/144758654-d2a639ee-fd41-4e84-884f-4f9d5fdc868b.jpg)

SRT with WebRTC is very sensitive to OBS settings. The thing that helped a lot was to set custom buffer size. Around 100 to 500 works for me (you can also try setting it to the same value as your bitrate, if it's not too high).
I notice that 0 buffer size, or too large buffer size introduces artifacts.
It can also happen if your upload bandwidth is actually not high enough compared to bitrate set in OBS.
I wouldn't recommend using CBR, ABR/VBR are actually much easier on the bandwidth for the same quality.

**Comment by zcolor** [comment]
Hi!

Thanks for the reply

It’s looks exactly like that!  


I’ll look into the setting on obs and report back! 

Thanks
Zé Maria Abreu Santos
e-mail: ***@***.***
tel: +49 (0) 173 876 00 33
web: zemariacolor.com

**Comment by zcolor** [comment]
Thanks for your comment. Changing the settings in OBS did the trick! 

I have a question though, SRT is by natively encrypted, correct? But the publishing via WebRTC isn't, right?

**Comment by getroot** [comment]
@zcolor WebRTC streams are also encrypted with DTLS + SRTP.

**Comment by zcolor** [comment]
Thanks! 

I’m still toying with the OBS settings but it’s not 100% there. I’ll have to check the xml when I got time. 

Zé Maria Abreu Santos
e-mail: ***@***.***
tel: +49 (0) 173 876 00 33
web: zemariacolor.com

**Comment by getroot** [comment]
@zcolor 
SRT is a protocol that applies encryption and stability (retransmission, FEC, etc.) based on UDP. So this does not recover 100% of the loss. The key feature is to recover the loss within the limits of the size and delay of the jitter buffer. If you don't like the loss of SRT, it's better to use a TCP-based protocol (like RTMP).

**Comment by zcolor** [comment]
@getroot thanks, 

I’m just trying it out for now, but I work in post production, l the idea of the stream being encrypted is a very attractive prospect. 

But are you saying the pixelation issue never completely goes away?

**Comment by getroot** [comment]
I developed by applying the SRT library, but I am not an expert in SRT. If the network condition between the SRT encoder and OME is very good, there should be no problem.
However, in networks that require a lot of packet recovery and reordering, this will depend on settings such as the buffer size of the SRT or the maximum delay allowed.
If you share what you learn later with this community, many people will like it.

**Comment by zygocact** [comment]
Yes, SRT is sensitive to connection quality. It requires that the frames arrive on time.
And I think it's more about stability / lack of jitter than max speed or anything.
I am fortunate enough to not have any problems, because of good internet connection.
Some of my friends, who have worse connection, experienced such artifacts, and we had to fiddle with OBS settings, and now it works fine for them, so it's definitely possible to find the "sweet spot"

Low latency RTMP also works, but I have discovered that in certain conditions, such as high latency, inefficient routing, packet loss, etc., RTMP just stops working, while SRT handles it. So it all depends on your conditions.

I had to switch from common VPS providers to Google Cloud, because common VPS providers often have inefficient routing problems, and congestion during peak hours, so delivering / receiving a stream is impossible if the ping to server is higher than 170. After switching to GCloud, I can stream to central USA server from eastern europe, to a client in australia, and it works fine.

It's a lot of trial and error, but in the end, you should be able to find settings that work for you.

**Comment by zcolor** [comment]
> I developed by applying the SRT library, but I am not an expert in SRT. If the network condition between the SRT encoder and OME is very good, there should be no problem. However, in networks that require a lot of packet recovery and reordering, this will depend on settings such as the buffer size of the SRT or the maximum delay allowed. If you share what you learn later with this community, many people will like it.<

I will definitely share whatever I find. This community has been great to me, I'll take every opportunity to give back.

**Comment by zcolor** [comment]
> 



> I wouldn't recommend using CBR, ABR/VBR are actually much easier on the bandwidth for the same quality.

I was under the impression anything other than CBR, OME couldn't handle very well.

**Comment by nxtreaming** [comment]
CBR should be the default rate control method in live streaming scenario.
VBR should be probibited in live streaming because it would cause congestion.

**Comment by Morpheus235** [comment]
Just to add my 2 cents. Were using official Haivision Hardware in our company this includes pretty much anything that haivision has to offer including their cloud services. While testing SRT with the official encoders we ran into a lot of out of order Errors even on a quality connection. This resulted in choppy playback which could be somewhat resolved by switching to webrtc Tcp. My guess is the missing option of configuring the threads options as in OBS. While Transcoding then also somewhat helps we then ran into issues with the Stream for example randomly disconnecting every few minutes. As far as I can guess this is related to the fact that the implementation of SRT in OME is focused on obs. I will setup a testing enviroment and provide some logs of the behaviour.

**Comment by zygocact** [comment]
> > 
> 
> > I wouldn't recommend using CBR, ABR/VBR are actually much easier on the bandwidth for the same quality.
> 
> I was under the impression anything other than CBR, OME couldn't handle very well.

> CBR should be the default rate control method in live streaming scenario. VBR should be probibited in live streaming because it would cause congestion.

It works for me. Although I do not transcode. I use bypass exclusively.
In OBS, ABR/VBR do not go over the bitrate limit in the settings, so it doesn't cause congestion for me. I don't really care for the reduced network usage in static scenes, because I usually stream dynamic video, but I've found that ABR/VBR give better quality than CBR, for the same bitrate.

![image](https://user-images.githubusercontent.com/75622726/145663198-22fe235f-f39d-46fd-ad51-ec85b856ba32.png)

**Comment by zcolor** [comment]
I'm looking at this app: https://srtminiserver.com/

SRTStreamer to see if it has better quality/lowerlatency than OBS but I can't figure out how to write the URL correctly

**Comment by zcolor** [comment]
> In OBS, ABR/VBR do not go over the bitrate limit in the settings, so it doesn't cause congestion for me. I don't really care for the reduced network usage in static scenes, because I usually stream dynamic video, but I've found that ABR/VBR give better quality than CBR, for the same bitrate.

Thanks for your reply. I tried your settings and still had decoding issues.

I have to drop the bitrate to 4000/3500 and then the quality suffers a bit.

I'm sticking to rtmp but I'll keep testing settings out

**Comment by Morpheus235** [comment]
> > > 
> > 
> > 
> > > I wouldn't recommend using CBR, ABR/VBR are actually much easier on the bandwidth for the same quality.
> > 
> > 
> > I was under the impression anything other than CBR, OME couldn't handle very well.
> 
> It works for me. At least at the lower bitrates and the resolution I stream with. Although I do not transcode. I use bypass exclusively.
> 
> > CBR should be the default rate control method in live streaming scenario. VBR should be probibited in live streaming because it would cause congestion.
> 
> In OBS, ABR/VBR do not go over the bitrate limit in the settings, so it doesn't cause congestion for me. I don't really care for the reduced network usage in static scenes, because I usually stream dynamic video, but I've found that ABR/VBR give better quality than CBR, for the same bitrate.
> 
> > While testing SRT with the official encoders we ran into a lot of out of order Errors even on a quality connection. This resulted in choppy playback which could be somewhat resolved by switching to webrtc Tcp.
> > This happens to me with OBS as well, on certain connections. The connection in my home over 5GHZ wifi works perfectly, but on work wifi, I get out of order packets. I suspect it's not just about total upload speed, but things like jitter, packet loss, etc. But maybe it is OME that is very sensitive to such things. I don't know, I don't have another super low latency WebRTC streaming engine to compare with :P.
> 
> ![image](https://user-images.githubusercontent.com/75622726/145663198-22fe235f-f39d-46fd-ad51-ec85b856ba32.png)

Well I already experimented a lot using Gstreamer/FFmpeg and Developing WebRTC based stuff. But yeah basically the Connection Quality is key which why we are relaying all our Streams using SRT gateway (Haivision Cloud Service) Which is basically a Cloud Router for SRT Streams.  Most of the time our latency is in the 20-100ms range while using a lot higher for the Socket options to get a stable jitterbuffer in case of drops. As far as I can say I only noticed errors on Ovenmediaengine Side of the whole Stream. While Playing the Stream on another Gateway Client was perfectly stable. I suspect some of the encoding Settings used by the Asics arent making the h264 decoder used in the browser happy. 

@getroot Is there any chance u guys might be interested in checking the SRT support to also accommodate this Hardware? We would happily provide access to one of our Hardware Encoders, Logs, etc as a testing env.

**Comment by getroot** [comment]
@Morpheus235 
Thanks for the great suggestion.

I haven't studied SRT properly yet. I just linked the library and did some basic testing. Maybe I didn't set the mandatory options to help the quality of the SRT. Or maybe there is a bug in OME's MPEG-2 TS Provider. I would be very happy if someone could post a PR for this.

Anyway, when I have some free time after a busy schedule, I will ask you to use an SRT encoder while studying SRT. thank you.

Before that, OME was still using SRT version 1.4.2 (a year ago). If your time permits, could you please check if the quality improves with the latest SRT 1.4.4? Just change to 1.4.4 in the code below. (Please, I hope it compiles and works well even if the version changes to 1.4.4.)

https://github.com/AirenSoft/OvenMediaEngine/blob/c8adc48069ffcaf6c075cb63e174f85b9acbe5ee/misc/prerequisites.sh#L9

**Comment by Morpheus235** [comment]
@getroot Im pretty busy till Wednesday but I will try to squeeze it in somewhere. I will update with some logs and my findings

**Comment by Morpheus235** [comment]
@getroot Well compilation worked flawlessly using the latest master. Out of order Errors still occur every ~ 10 seconds and result in stuttering occuring in the webrtc stream. Other Protocols seem to be unaffected. Since I ran my test using default logging options I will try to setup the srt logging params to be more verbose. Also the lastest update of the uswd encoder introduced a lot of changes (support for slices, fec, utc timing for video) but neither of the supported timing behaviours seems to change anything. But besides the out of order error the stream seems to be stable and webrtc-internals stats also supports this as all metrics seem to be normal.

**Comment by getroot** [comment]
Thanks for the analysis.

An out-of-order error occurs when the sequence numbers of MPEG2-TS packets are not sequential. We didn't implement a buffer for this in OME, as we expected SRT level to handle these issues.

Previously testing this with OBS or ffmpeg on a local network did not reproduce the problem. Is there some bug in OME? Or maybe the SRT doesn't handle that well? I will analyze this issue in depth later.

**Comment by Morpheus235** [comment]
Yeah thats what I figured and already had a look in the implemented counting in [mpegts_depacketizer.cpp](https://github.com/AirenSoft/OvenMediaEngine/blob/a417a46bbae67b5f7e0a1549996c008ccf0defbf/src/projects/modules/mpegts/mpegts_depacketizer.cpp#L54) and informed myself about counting in mpegts transports. While doing this I stumbled upon duplicate checking and that a packet under certain circumstances does not increase the 4 bit counter.
These are:
a) Packet has no payload
b) The discontinuity flag is set
c) Packet is a duplicate of the last packet

While looking through the Code I only figured that discontinuity indicators arent being looked at if I am not mistaken.

So maybe packets that are being resent due to loss are also used for counting? But thats just my guess.

Also SRT Release [1.4.4](https://github.com/Haivision/srt/releases/tag/v1.4.4)  seems to be adressing a lot of issues in SRT Group connections.


Further Information:
[tsduck Issue](https://github.com/tsduck/tsduck/issues/256)
[stackoverflow](https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github)

**Comment by zcolor** [comment]
>I'm looking at this app: https://srtminiserver.com/

SRTStreamer to see if it has better quality/lower latency than OBS, but I can't figure out how to write the URL correctly 

I finally got the URL naming right. I made it work, but it uses b-frames there’s no option to disable it. I'll keep looking for a solution.

**Comment by basisbit** [comment]
Fyi, I have been using SRT a lot in the past half year for international video streaming. TLDR: Drop using rtmp, srt is so hugely much more stable/reliable and more consistent especially for low latency streaming.

See this for how to properly build the stream server url that is to be used for OBS and similar (imho the OME documentation on this is still awfull): https://github.com/AirenSoft/OvenMediaEngine/issues/454#issuecomment-903177699

The no b-frames requirement is not a requirement form SRT, but instead is a requirement for WebRTC. Twitch, YouTube and similar avoid such problems by always transcoding incoming video feeds unless they perfectly fit their requirements.

**Comment by nxtreaming** [comment]
> Fyi, I have been using SRT a lot in the past half year for international video streaming. TLDR: Drop using rtmp, srt is so hugely much more stable/reliable and more consistent especially for low latency streaming.
> 
> See this for how to properly build the stream server url that is to be used for OBS and similar (imho the OME documentation on this is still awfull): [#454 (comment)](https://github.com/AirenSoft/OvenMediaEngine/issues/454#issuecomment-903177699)
> 
> The no b-frames requirement is not a requirement form SRT, but instead is a requirement for WebRTC. Twitch, YouTube and similar avoid such problems by always transcoding incoming video feeds unless they perfectly fit their requirements.

SRT is only reliable when the packet loss ratio is very small , such as <3 %,  srt will delivery huge masic if the packet loss ration is not stable, ie from 3% to 23%.

**Comment by basisbit** [comment]
if your internet connection constantly has 23% of packet loss, then it is unusable, because TCP connections will never reach usable throughput speeds. For short bursts of packet drop, SRT handles them much better than rtmp, especially at higher network latency / distance to the server - but it requires you or the OBS user to set a fitting latency value as part of the url (at least 2.5x the ping / roundtrip time is the recommendation from the OBS dev team, and that also worked well from my experience).

You always have to look at `packet loss x latency` product to do real world comparisons. For doing decent comparison tests, I suggest using tools like Clumsy (https://github.com/IntouchHealth/clumsy) to get reliable and reproducible bad different network environments.

**Comment by nxtreaming** [comment]
@basisbit 
Which SRT server do you use？

**Comment by basisbit** [comment]
OBS -> OvenMediaEngine

**Comment by Morpheus235** [comment]
So for everyone not being so sure about setting up an SRT stream or available parameters, Haivision offers a Deployment Guide going into detail how its done:
[Deployment guide](https://www.google.com/url?sa=t&source=web&rct=j&url=https://zest-technologies.co.uk/wp-content/uploads/2021/03/SRT_DeploymentGuide_v1.3_2019-05-21.pdf&ved=2ahUKEwi8t56Q4I71AhVbSfEDHbLqCO4QFnoECCwQAQ&usg=AOvVaw0870hLP5_YFY-KbAbalmkW) 
[SRT socket options ](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md)

**Comment by 3dcandy** [comment]
basisbit is on the money. SRT and webrt are both lots better than rtmp with some tweaking. For example setting a latency figure of 5 seconds gives you effectively a 5 seconds buffer to ensure the packets reach the destination. This overcomes many issues that a poorer connection might have as long as the stream is being rendered on time and correctly by say your OBS settings

**Comment by basisbit** [comment]
Had a couple of fandom conventions already do live streams of their events from hotels with super shitty internet connections, and SRT so far always performed a LOT better than RTMP. If necessary, just up the "latency"/buffer size to 7 seconds, and always make sure to not use more than 40% of the local internet upload speed as video bitrate (so that SRT has a chance to resend lost frames when necessary).

**Comment by 3dcandy** [comment]
exactly - for me so far, from a half decent wifi hotspot connection through a cell/mobile connection 5 secs has worked. But that's basically 1 machine using the connection and any others using their own wifi/cell connection. The ingest server is running on a cloud instance and then pushes the stream wherever and it's been 100% reliable. Test the connection first and adjust as necessary
