### ISSUE TITLE
Limit bitrate server side?

### ISSUE THREAD

**Issue by Adam1901** [AirenSoft/OvenMediaEngine#599]
Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**

I want to be able to limit the incoming bitrate.

**EXPECTATION**

An override in the origin.xml? Or admision webhook?

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

Please check whether it is reproduced in the master branch first. The Docker image for the master branch is airensoft/ovenmediaengine:dev .
If you are using the Master branch, please write Master.
If you are using Release, please write the version (eg 0.12.4). 0.12.9 docker imange
If you are using Docker by building it yourself, please tell us what version of the image you built. 
If you are using a public Docker image, please provide the image path with tags. (e.g. airensoft/ovenmediaengine:0.12.8)

My docker image
`FROM airensoft/ovenmediaengine:0.12.9

COPY Server.xml /opt/ovenmediaengine/bin/edge_conf/Server.xml
EXPOSE 80/tcp 7080/tcp 7090/tcp 1935/tcp 3333/tcp 3334/tcp 4000-4005/udp 10000-10010/udp 9000/tcp
CMD /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf
`

- Encoder information

What encoder are you using?(e.g. OBS 10.22) And how is the codec set on that encoder? Any OBS version or other client

**Comment by getroot** [comment]
It is very difficult to limit (in the case of VBR) as the bitrate can constantly change during transmission. Even CBR can intentionally increase the bitrate, and some encoders do that.

To make this possible, OME needs a module that keeps on detecting bitrates in real time and the ability to forcefully terminate that stream. And such a feature is not available in OME.

**Comment by getroot** [comment]
This is hard to control with AdmissionWebhooks.

Information such as Resolution, FPS, Bitrates, and Samplerate may be provided depending on the encoder or protocol, or may not be provided. Because this is just meta-information and not a required value.

The only way to get track information is to get the actual stream and analyze it. AdmissionWebhooks are out of time because they are triggered before receiving the actual stream data from the client.

To handle this, as I answered in the issue below, OME needs to add a real-time stream information analysis module.

https://github.com/AirenSoft/OvenMediaEngine/issues/599

**Comment by naanlizard** [comment]
We are also interested in such a feature, though for the time being, with existing OME features we can limit the playback of high bitrate streams on the frontend - perhaps this would help you @Adam1901

**Comment by getroot** [comment]
I was looking at an old issue and found that there was a duplicate issue. #201
Let's discuss this feature in #201.
