### ISSUE TITLE
Ultra-Low-Latency definition

### ISSUE THREAD

**Issue by dtaht** [AirenSoft/OvenMediaEngine#603]
In my world ultra-low latency typically means a 1-6ms RTT for a network. See L4S networking as one example. 

Also I do hope you are using various debloating techniques on the network sides of your streams - TCP_NOTSENT_LOWAT as one example, recommending streamers use "smart queue management", and so on.

**Comment by getroot** [comment]
We're not alone in using the term ultra-low latency streaming. This is a term used by everyone in the streaming industry for lower latency because HLS, the most used streaming protocol, has a latency of 6 to 30 seconds.

In streaming, we usually say ultra-low latency when the mirror-to-mirror latency is sub-second.

There are many articles from the streaming industry below.

https://aws.amazon.com/media/tech/video-latency-in-live-streaming/

https://kr.limelight.com/blog/capitalize-on-ultra-low-latency-streaming/

https://corp.kaltura.com/blog/low-latency-streaming-guide/

https://support.google.com/youtube/answer/7444635?hl=en#zippy=%2Cultra-low-latency

Thanks for pointing out options like TCP_NOTSENT_LOWAT . I'm going to study this.

**Comment by dtaht** [comment]
I don't mind that the phrase is overloaded.  (example: https://riteproject.eu/dctth/ ) but there is a semantic gap between what the AQM folk are trying to achieve - sub 5ms queuing delay - and "sub second" streaming delay that someday we should come up with a common phrase for. In my mind queuing delay is probably one of the biggest factors in streaming anything in general - with a range from 0 to many seconds. Notably the fq-codel algorithm and sqm can cut queuing delay significantly, but it helps if the streamer is responsive to congestive signals like loss, ecn markers and delay.

**Comment by getroot** [comment]
Well... you created this issue with the label "bug". 
I don't quite understand your intentions.
So what do you think should be fixed in OvenMediaEngine?

**Comment by basisbit** [comment]
Also, please keep in mind that these queueing mechanisms that were suggested perform poorly over the internet with high concurrent users count.

**Comment by dtaht** [comment]
Is there another label besides bug? What I was looking for was trying to A) come up with a common set of phrases that described sub-frame (?) latencies since until now I thought you meant the same thing with ultra-low that we did...

And B) try to discover to what extent you were using congestion control mechanisms such as this:

https://github.com/zenomt/rtmfp-cpp#delay-based-congestion-detection

And C) come up with metrics that matter, per the recent iab workshop: https://www.iab.org/activities/workshops/network-quality/

**Comment by basisbit** [comment]
@dtaht sorry, but how do you think a for example 300ms time frame, where no data can be transferred between server and client including roudtrip), should be handled without client side playback buffer that is substantially longer than this (or is stretched to be longer)?
Such dropouts are rather common, because of either a fiber-cut on the way, or BGP route change / failover or an unexpected noise source on the last mile / or on shared medium (like WLAN or DOCSIS based copper TV network or GPON and so on).

OvenMediaEngine, its Origin-Edge Architecture, the supported origin input feeding protocols SRT and RTMP, as well as how typical tools like OBS are designed, are optimized for high quality streaming over long distance networks at low cost and low bitrates while being without loss of frames and without stuttering/stretching. This can only be achieved with having buffers that can hide most of the commonly happening transmission interruptions. In the video streaming branch, reducing these buffers to almost only exist at the video rendering client and passing frame data asap in between, is what is commonly described as "Ultra-low latency" video streaming.

Other use cases like realtime video conferencing (BigBlueButton, Jitsi, Zoom,...) however are not optimized for showing video data without interruption, but instead they are optimized for playing the data as soon as it arrives (only using a small jitterbuffer of typically 20 to 100ms - and growing it on demand to maybe 400ms for some cases).

> In my world ultra-low latency typically means a 1-6ms RTT for a network.

Sorry, but in what world are you living??? Those numbers are only remotely interesting for MAN or corporate internal / intra-building networks. For reasons of cost reduction in combination with scaling efficiency issues as well as physical limitations, neither do different ASs typicalls peer in the city where the user is, nor do service providers (not even Akamai) operate edge servers in every city (and then peer with every AS in that city).

Thus, please forgive me, if I am wondering how useful it would be to keep this issue here in the OvenMediaEngine issue tracker (which is about improving OME as a software) open.



> Also I do hope you are using various debloating techniques on the network sides of your streams - TCP_NOTSENT_LOWAT as one example [...]

Uhm, there exists UDP based WebRTC stream transmission, so no need for TCP flow control / congestion avoidance micro-optimizations which cost extra CPU cycles. For the TURN server however (which is to be used when the user can't receive frame data over udp), that is a different topic.

**Comment by getroot** [comment]
We are interested in sending live video end-to-end in sub-seconds.

WebRTC is basically UDP based, so it has nothing to do with congestion control. WebRTC/Turn/TCP, RTMP, HLS, and MPEG-DASH are TCP-based, but only the congestion control provided by the kernel can be used. I am recommending BBR to users. In my tests, the BBR performs well enough at scale.

https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#5-3.-congestion-control-change-to-bbr

In the case of SRT, I believe that it handles congestion control itself well. Wouldn't it be better for you to discuss it on SRT (https://github.com/Haivision/srt)?

We are not a team developing new protocols. We are a team that is developing a large, ready-to-use ultra-low latency streaming server based on the WebRTC protocol.

**Comment by dtaht** [comment]
The most common congestion control algorithm for webrtc is called "google congestion control", gcc for short. UDP needs congestion control as much or more than tcp does. https://datatracker.ietf.org/doc/html/draft-ietf-rmcat-gcc-02

**Comment by dtaht** [comment]
And thank you very much for that link: https://datatracker.ietf.org/doc/html/draft-sharabayko-srt-01 - yes, now

I am not particularly fond of BBRv1, which can basically only adjust in a 10sec interval. BBRv2 is better, but gcc + svc is working out fairly well in the galene.org testbed. I am curious how long it takes to switch encoders when congestion is experienced?

**Comment by getroot** [comment]
@dtaht 

OvenMediaEngine is a streaming server that delivers streams to tens of thousands of people simultaneously. OvenMediaEngine is aimed primarily at users who want to deliver 1 rtmp input from an encoder to tens of thousands of webrtc players. So this can't be done with real-time encoders like p2p or small SFUs (webrtc to webrtc). Instead, it pre-encodes the stream to three or more bitrates and delivers it as an ABR stream.

In the WebRTC/udp output situation (OME to viewers), what OvenMediaEngine does is very limited. It supports RTX, but when the player (browser) sends a NACK, it is retransmitting it immediately. I expect the browser to detect congestion and send a NACK, OME does not. And since this retransmits the live streaming input, the packets are sent immediately as they come in, without buffering.

In the WebRTC/udp input situation (Browser to OME), the congestion control is done well by the browser, and OME has little to do with anything other than sending the RTCP RR well.

I think that WebRTC/tcp shows better quality than WebRTC/udp in environments that need to provide high-quality streaming on a large scale. It's already proven, and it's easy to use. In fact, a large Korean live commerce company is successfully streaming to about 5000 concurrent users with this. WebRTC/udp seems to be difficult to apply to actual commercial environments no matter how well it controls congestion in large-scale, high-quality streams. Of course, WebRTC/udp would be much more suitable for small online meetings.

SVC...if all browsers support it, we will definitely support it in the future. At that time, all browsers will probably support the VP9 or AV1 codec. As you know, currently the only codec that can be used in commercial environments is the H.264 baseline.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
