### ISSUE TITLE
SRT input from Haivision Makito

### ISSUE THREAD

**Issue by rubikean** [AirenSoft/OvenMediaEngine#606]
I am using Makito X4 encoders and would like help to understand how to format the encoder setting to connect and transmit an SRT stream. 
I do not understand how to format the percent encoded url into the Makitos settings. Can you suggest a method?

The error from OME is-  
The SRT client has connected : <ClientSocket: 0x7f8758006ef0, #418878303, Connected, SRT, Nonblocking, 192.168.32.19:58107> []
SRT's streamid streamid must be in the following format, percent encoded. srt://{host}[:port]/{app}/{stream}?{query}={value} :

Here is the Makito Interface- 
![Capture](https://user-images.githubusercontent.com/11854499/146791751-c4bda341-3243-40e3-b468-66a540ba8e9a.JPG)

-Chris

**Comment by getroot** [comment]
I have no experience with that encoder, but... Guessing through the UI

The `Stream Publishing ID` seems to be streamid. If that is correct, you can write the `Stream Publishing ID` as below.

`srt%3A%2F%2F{domain or IP address}[%3APort]%2F{App name}%2F{Stream name}
`

The manual is below.

https://airensoft.gitbook.io/ovenmediaengine/live-source/srt-beta

**Comment by Morpheus235** [comment]
@rubikean Well our comapny uses Makito X1, X4, etc.  So I am familiar with the connection procedure. Basically select `Custom` as Format in  `SRT Acess Control`  and then just enter the percent encoded URL as given by getroot 

short example:

>const url = "dev2.airensoft.com";
const port = "9999";
const stream = "stream";
const app = "app";
console.log(encodeURIComponent(\`srt://${url}:${port}/${app}/${stream}\`))

![image](https://user-images.githubusercontent.com/40322103/147210856-36e55442-9d48-45c2-bbb9-272cd5005f2e.png)

**Comment by zcolor** [comment]
@Morpheus235 do you find the hardware encoder adds more latency than a software encoder? The best performance I got so far was with OBS. I tested the Blackmagic Web presenter and the aja hello and both added some latency.

**Comment by Morpheus235** [comment]
@zcolor Depends the hardware encoders are actually more comparable with gpu encoders as they are using asics. We also have a bunch of haivision decoders abd with these the latency is barely noticeable. Regarding Ovenmedia probably WebRTC will offer the least amount of latency which is why im trying to get ovenmediaengines webrtc endpoint to work with a custom gestreamer Pipeline. For other  SRT streaming software for example: tsduck,srt-live-transmit(shipped by haivision in the srt repo), haivision play(mobile), nimble streamer,vmix to name a few. In my opinion OBS just isnt stable enough as a streaming software as the SRT implementation in OBS leaves a lot to be desired e.g. OBS always deadlocks for me on a non sucessful srt connection due to bad url or in case of obs policy and Signature. Also depending on the workload the encoding can get quite taxing on the cpu while the x1 for example tops at 8 watts offering two video and audio encoders

**Comment by zcolor** [comment]
I tried opening an SRT stream going through OME on the haivision mobile app but didn't have any luck.
