### ISSUE TITLE
Feature request: HTTP-FLV Publisher

### ISSUE THREAD

**Issue by XuanTung95** [AirenSoft/OvenMediaEngine#700]
**Is your feature request related to a problem? Please describe.**

I found that some big apps use http-flv for live-stream and HLS for playback.
After some testing, I see that the performance of http-flv is quite good and the latency is low.
Android supports it by default.
Ios does not support flv but I can use libVLC or other libraries to play it.
I think many people will choose http-flv over its advantage.
Please consider.

**Additional context**
Some article: https://www.yanxurui.cc/posts/server/2017-11-25-http-flv/

**Comment by getroot** [comment]
My opinion is that flv has already ended support with flash, and there is no chance that new codecs will be supported in the future. Also, since it can't be played on the mobile web (especially iOS Safari), I don't think many users will choose it. Support for the player SDK is also very limited.

Standard low-latency streaming protocols such as WebRTC and LLHLS are already widely used. In addition, it supports ABR, Multi track, new codecs (H.265, VP9, AV1), SVC, etc., and continues to evolve. And many platforms and players already support this protocol. So I think OvenMediaEngine should focus on WebRTC and LLHLS. There are many features that have not been implemented yet.

Thanks for the good suggestion.

**Comment by XuanTung95** [comment]
Thanks for your response.
I really appreciate this project.
I close this.
