### ISSUE TITLE
High WebRTC latency

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#738]
When CPU usage approaches 100%, with relatively large numbers of users (for us) connected - maybe 50-100 viewers spread across streams connected via WebRTC and others connected via HLS, WebRTC is showing a 15+ minute delay for some users. This is on a Ryzen 5950x, so 16c/32t, very powerful

Is this something others have experienced? I was under the impression some Airensoft customers were very large stream setups, though perhaps they have much more CPU resources to support that?

We're still experiencing abnormally high CPU usage from OME but we are planning several benchmarks to narrow that down, along with our freezing issue (still), and perhaps it is all related.

**Comment by naanlizard** [comment]
In what may be a bug report, it appears that if webrtc latency is high, the stream going offline callback is delayed as well. This leads to buffering HLS playing the last few seconds of the stream whenever you load the stream, and webrtc playing back old content.

The offline callback did go through before it ran all the way through the webrtc backlog for the stream I was watching though, which was interesting

**Comment by getroot** [comment]
When the CPU is 100% used, the processing speed will be slow (typically WebRTC SRTP encryption, HTTP/TLS encryption), so the packet queue will gradually grow and latency will continue to increase. Also when you use 100% of your CPU, you can run into any issues, not just this.

The large video platform I operate has handled up to 15,000 concurrent users, and there is only one input stream. It consists of 2 Origins (Active-Standby) and 15 Edges. One Edge serves about 1000 viewers. Edge's CPU power is used only for transmission, and all roles such as encoding/recording/thumbnail extraction are performed by Origin. Rather, Origin doesn't use power for viewers. This makes thread optimization more concise. Origin allocates threads to AppWorker and Edge allocates threads to StreamWorker.

And all the servers I operate are installed directly on the server host and do not use Docker. Because I think I don't know much about Docker yet.

In the server configuration you run, both AppWorker and StreamWorker threads are allocated a lot, so it is very difficult for me to predict the state, but I guess that it is probably using a lot of CPU when opus encoding/Thumbnail encoding of multiple input streams. Use a command like top -H -p [pid] to check which task (thread) is using the CPU a lot. Even if the CPU is not used 1600% (when 16 cores), if any thread uses 100% of one CPU core, it will definitely become a bottleneck, so you need to expand that thread or shrink other threads.

For reference, SRTP encryption uses most of CPU power when streaming webrtc with transcoding bypass setting that does not encode any.

**Comment by naanlizard** [comment]
Naturally, when things get to 100% CPU that is prone to all sorts of weird stuff happening. Perhaps WebRTC should do something to catch up more rapidly?

The largest concern I had was with the delayed "stream ending" callback

What CPU are your edge servers using, if I may ask?

**Comment by getroot** [comment]
The CPU of that Edge server is Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz. But it operates as Edge, so it doesn't do anything other than deliver WebRTC streams.
