### ISSUE TITLE
[FR] add http-flv publisher support

### ISSUE THREAD

**Issue by syklevin** [AirenSoft/OvenMediaEngine#75]
First of all thanks for the great project.

In H5 live stream industry, using rtmp protocol (which need a flash client on client side) is not a good choice and most broswers will drop support flash very soon.

there is already a well known [flv.js](https://github.com/bilibili/flv.js) library used in many of companies for doing live stream purpose and the latency could achieve as same as rtmp. 

I think it is definitely a value-added feature for composing those pioneer techs (webrtc, cmaf, and httpflv) in H5 low latency stream industry.

**Comment by dimiden** [comment]
@syklevin 
Thank you for your good feedback!

I'm hesitant to develop ```http-flv``` feature due to some limitations:

- iOS doesn't support Media Source Extension.
- RTMP doesn't support various codecs such as H.265/OPUS.

We will be developing RTMP publishers in the future, so we will discuss this feature with OME developers.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
