### ISSUE TITLE
Restricting Playback to a Specific Domain

### ISSUE THREAD

**Issue by budocski** [AirenSoft/OvenMediaEngine#761]
**PROBLEM**
I am trying to restrict playback to a specific domain as anyone with the source url can play the live stream. I tried using Admission Webhooks but its missing a "referer" header that I can possibly use in this scenario.

**EXPECTATION**
Is it possible to add the domain referer from the admission webhook request?

**ENVIRONMENTAL INFORMATION**
I am using the latest version of the OME.

**Comment by IanMitchell77** [comment]
If the data to the control server could also include the user agent string of the browser that'd be helpful too.

**Comment by getroot** [comment]
Referers and user agents are easy to manipulate, so I think it's not a good way to limit playback. It is recommended to use CORS instead.

WebRTC is using websocket for signaling, so you can't use CORS. Instead, you can fully secure it using the following method: This is a rough idea, so it can be applied in various ways by using `new_url`.

https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks

1. Distribute the following URL to users

wss://domain:port/<encrypted-user-information>

2. AdmissionWebhooks asks your Control server to play the URL.

3. Your control server decrypts <encrypted-user-information> to read the user information. Checks if the user has paid you or is an authenticated user, and if so, returns the normal url in the `new_url` field

[more ideas]
- In encrypted_user_information, information about URL expiration can be included so that playback can be rejected when it has been issued for a long time.
- By inserting session_id into encrypted_user_informaiton, playback can be rejected if the number of playbacks is more than twice. (Update that information in your db)

4. Only authorized users can get the playback URL

**Comment by budocski** [comment]
My system works like this. My website has a publicly available live stream video that anyone can play as long as it is under the domain of my website. 

e.g: https://myovenplayer.com/player?id=100005

But someone with a good knowledge of how live streaming works can easily get the source of the video and play it on their own website. That is what I wanted to avoid. Are there any options?

**Comment by budocski** [comment]
_Your control server decrypts <encrypted-user-information> to read the user information. Checks if the user has paid you or is an authenticated user, and if so, returns the normal playable URL (eg. wss://domain:port/app/stream) in the new_url field_

In this method, will the user see the new_url passed by the control server? If so, then any authorized user that has access to it can distribute the new_url and play it on their own website. So I think this is also not possible in my model.

**Comment by getroot** [comment]
Users can not know the new_url. Only OME know that. And even if users know the new_url, your server can reject requests to play with the new_url.  All incoming requests to OME are directed to the Control server.  And OME plays the new_url to which the Control server responds.
