### ISSUE TITLE
Question: Which Server handles encoding in Origin-Edge-Cluster?

### ISSUE THREAD

**Issue by NK0D1NG** [AirenSoft/OvenMediaEngine#772]
**Question**
According to the docs (https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering) an Edge Server pulls a Stream from the Origin Server if a user requests it. My question is: Which Server does the transcoding?

For example:
The Player of the user's browser requests a HLS stream from the edge server. Is the edge server now delivering the .m3u8- and .ts-files by itself? If yes than the edge server would need to request the stream from origin via RTSP/OVT and encodes it to HLS itself and returns those HLS files to the user's browser. If not, the edge would request the HLS files from the origin. In this case, the traffic would arise at the origin server and the whole clustering would be kinda useless.

**EXPECTATION**

I would expect some more information in the documentation about the configuration of origin and edge server and more details about the tasks. It would be also very helpful to provide some information about which service/port needs to be configured on which server. Which server does the transcoding, which server handles traffic? What happens if the edge server pulls the stream via RTSP/OVT? What about the outgoing protocols like HLS/WebRTC...

**OTHER HELPFUL INFORMATION**

I would be glad to help extending the documentation in this topic and providing more detailed information from real production scenarios (for example using docker swarm and traefik as a loadbalancer). But therefore I need to understand the mechanism of the origin-edge-structure OME provides.

Thanks for this awesome project and greetings!

**Comment by getroot** [comment]
It depends on what you set in Server.xml, but in most cases, it is encoded by Origin. (In the case of a stream received through OVT, even if you set the encoding to Edge, it does not work. This is a part that will be changed soon.) We do not restrict the roles of Origin and Edge, which can make Origin-Relay-Edge work in some environments. Because there is also. Relay is not only Edge, but also Origin.

Encoding and Packaging are different. Encoding is at the codec level, and Pacakaging is at the container level. What makes a TS file is packaging. First of all, I hope this terminology is clear.

Not all requests coming to Edge are required back to Origin. Streams that Edge already have are output from Edge immediately without requesting it back to Origin. So clustering works.
