### ISSUE TITLE
mpeg2 TS codecs

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#787]
hello, MPEG 2 TS udp input is only supported by ovenmediaengine with AAC codec for audio. In the near future will OME support more audio codecs?

**Comment by getroot** [comment]
Essential audio codecs will be updated. But I haven't yet found any essential audio codecs other than AAC and OPUS in MPEG 2-TS.

OPUS is a required codec because it is a codec that can provide WebRTC streaming without encoding in OME. However, OPUS has not yet completed the MPEG 2-TS encapsulation specification, so I am waiting for this. For more information on this, refer to the "Opus in MPEG2 Transport Streams" specification at https://opus-codec.org/docs/.

Please suggest anything else that you think is an essential codec. PR is also welcome.

**Comment by basisbit** [comment]
Does this also affect opus over SRT streaming? (afaik SRT makes use of mpegts?) Would be nice to be able to avoid the audio quality loss from converting the incoming AAC to Opus for WebRTC playback.

**Comment by getroot** [comment]
@basisbit 
SRT uses MPEG 2-TS container to transmit media. Therefore, when Opus is officially included in MPEG 2-TS, SRT will be able to transmit Opus.
