### ISSUE TITLE
minimum requirements

### ISSUE THREAD

**Issue by javier171188** [AirenSoft/OvenMediaEngine#796]
Hello, this is my first time opening an issue, I hope I follow the instructions correctly. 

**PROBLEM**
I would like to know the minimum requirements for the ovenMediaEngine to work correctly. Since I think this depends on the use case,  I would like to know about 2  streams and 200 viewers connected to each stream.

**EXPECTATION**

I would like to have a list of requirements, for example, the list for AOE4 is

Requires a 64-bit processor and operating system.
OS: Windows 10 64bit | Windows 11 64bit.
Processor: Intel Core i5-6300U or AMD Ryzen 5 2400G | CPU with AVX support required.
Memory: 8 GB RAM.
Graphics: Intel HD 520 or AMD Radeon RX Vega 11.
DirectX: Version 12.
Storage: 50 GB available space.

Or a way to get the minimum requirements for my use case.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

I am using  the image airensoft/ovenmediaengine:latest

- Encoder information

The provider is webrtc and the publisher is llhls.  

The encoders are:

<Video>
	<Bypass>true</Bypass>
</Video>
<Audio>
   <Bypass>false</Bypass>
  <Codec>aac</Codec>
 <Bitrate>128000</Bitrate>
</Audio>

Thanks for your help.

**Comment by getroot** [comment]
Performance is highly dependent on input/output bitrate. And there are many variables. For example, if the input is RTMP and the output is WebRTC, then there is the cost of encoding AAC to Opus. If your input is WebRTC and your output is LLHLS, you will incur the cost of encoding Opus to AAC. If you use thumbnails, there is an additional cost to encode them as JPEG or PNG.

Since there are so many cases, no one can guide you on the minimum system specs.

We provide a tool called OvenRtcTester to measure performance. However, this is only a measure of performance in relation to the number of viewers.

https://airensoft.gitbook.io/ovenmediaengine/performance-tuning#getting-started-ovenrtctester

Measure your case across different instance types in the cloud.

**Comment by javier171188** [comment]
Thanks for your answer.
