### ISSUE TITLE
linux kernel 5.4 change is necessary?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#804]
Status of OME on ubuntu 18.04.6 terminal notifies the existence of a linux bug on kernels 5.3 to 5.6...it is really something critical, should I consider changing Kernel?...I would like to try OME on ubuntu 22.04, its default kernel is version 5.15, however I don't know if OME can work on ubuntu 22.04.

**Comment by getroot** [comment]
https://bugzilla.kernel.org/show_bug.cgi?id=205933

This kernel bug causes OME's socket to freeze intermittently, during which time OME loses received packets. Since the freeze time is very short and the player will reconnect, the problem is resolved naturally. However, since it occurs intermittently, it will cause poor service quality in commercial services.

I use Ubuntu 20.04. I also haven't tried Ubuntu 22.04 yet.

**Comment by Mariano245** [comment]
Is it possible to change the kernel version, without having to reinstall OME?... what version of Kernell do you recommend?

**Comment by getroot** [comment]
Hmmm... If you update your kernel, it's a good idea to reinstall OME. It seems to work fine without reinstallation, but I'm not 100% sure of that. Also I don't know about kernel version. The only thing I know about is a bug in 5.3 that once bothered me.

**Comment by naanlizard** [comment]
Which kernel versions is this on? 5.3 to 5.6?

**Comment by getroot** [comment]
@naanlizard 
As far as I know, yes.
See https://bugzilla.kernel.org/show_bug.cgi?id=205933 for details.
