### ISSUE TITLE
LLHlsSession::OnMessageReceived(31) - Invalid stream key while on 2 Edge instances

### ISSUE THREAD

**Issue by sebdott** [AirenSoft/OvenMediaEngine#837]
**PROBLEM**

I'm currently working with the Edge server and have gotten it to work, but when I try to scale it to two instances, I get errors like the ones below in my logs.

[33m[2022-08-02 00:39:13.810] W [StreamWorker:202] LLHLS Publisher | llhls_session.cpp:196  | LLHlsSession::OnMessageReceived(31) - Invalid stream key : yJNAdgRl (expected : 8TLxV19t)[0m
[33m[2022-08-02 00:39:25.578] W [StreamWorker:202] LLHLS Publisher | llhls_session.cpp:196  | LLHlsSession::OnMessageReceived(31) - Invalid stream key : yJNAdgRl (expected : 8TLxV19t)[0m
[33m[2022-08-02 00:39:29.456] W [StreamWorker:202] LLHLS Publisher | llhls_session.cpp:196  | LLHlsSession::OnMessageReceived(31) - Invalid stream key : yJNAdgRl (expected : 8TLxV19t)[0m
[33m[2022-08-02 00:39:35.465] W [StreamWorker:196] LLHLS Publisher | llhls_session.cpp:196  | LLHlsSession::OnMessageReceived(25) - Invalid stream key : yJNAdgRl (expected : 8TLxV19t)[0m

Streaming appears to be working properly, but some streams appear to load slowly at first.
If I change to 1 edge server it will not have such an issue.

**EXPECTATION**

The Edge server should function normally without the above log errors.
The initial load should work normally

Would like to understand what is this error about.

**ENVIRONMENTAL INFORMATION**

Docker Image - airensoft/ovenmediaengine:latest

- Encoder information
OBS

- Player information

https://demo.ovenplayer.com - LLHLS

- URL

https://XXX/app/stream/llhls.m3u8)

- Operating system and version

Ubuntu 20.04 LTS

**SETUP INFORMATION AND LOGS**

[logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9238213/logs.txt)
[edge.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9238215/edge.xml.txt)

**Comment by getroot** [comment]
OME Edge is not an HTTP reverse proxy. Edge does its own packetizing. (This is an advantage when using OME as WebRTC edge)

It has the following characteristics:
- When the stream is initially pulled from the origin, it takes time to create several chunks. Once a stream is created, players who connect next can play it immediately.
- The player must always access the same edge. Use sticky mode on your load balancer.

Therefore, as an edge for LLHLS, it is better to use a CDN service like CloudFront or HTTP reverse proxy software like nginx rather than OvenMediaEngine.

**Comment by sebdott** [comment]
Thanks got it once more!
