### ISSUE TITLE
OPUS codec - low audio samplerate

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#859]
Hi,
It looks like some commit has broken sample rate for OPUS codec between 0.14.4 and 0.14.5 OME version.

```
<Audio>
	<Codec>opus</Codec>
	<Bitrate>320000</Bitrate>
	<Samplerate>48000</Samplerate>
	<Channel>2</Channel>
</Audio>
```
I have Samplerate = 48000 but there is noticeable diffrence between 0.14.4 and 0.14.5:
![spek_HBcpKGare9](https://user-images.githubusercontent.com/46460263/185250564-0ebde716-acc1-4161-bf5c-79937ba7d667.png)

I would like to ask you to verify that something has not been overlooked / changed by accident.
Maybe with this commits? https://github.com/AirenSoft/OvenMediaEngine/commit/f350d4c9f148d5f5253269399b0b69cbda5fbdec https://github.com/AirenSoft/OvenMediaEngine/commit/a69afd94341fd8ae6b6cc1775c04b0304a311595

**Comment by Keukhan** [comment]
@fcqpl 

Thanks for the great report. after 0.14.5 version, there was an audio frequency limit when encoding opus.
Exactly, the sample rate wasn't broken. It limits the audio frequency range.
Fortunately, there is no problem even if the audio frequency band is set to FullBand (~20Khz) because the sample rate is 48000Hz by default.

opus audio service quality has improved thanks to your reporting.

[Before]
![image](https://user-images.githubusercontent.com/21077363/186428380-25f362d6-5ab7-430c-b288-4795e9a47713.png)

[After]
![image](https://user-images.githubusercontent.com/21077363/186428587-2739ea74-eca5-4124-b991-6285241c4ae0.png)


https://github.com/AirenSoft/OvenMediaEngine/compare/a6e589fa9a07...3e531450905c
