### ISSUE TITLE
Memory leak (memory continue growing with a single RTMP Push)

### ISSUE THREAD

**Issue by radar155** [AirenSoft/OvenMediaEngine#951]
**Describe the bug**
I'm experiencing memory leaks. After I push data with a single RTMP streaming (with OBS), memory usage starts growing, even without any viewer. If you wait, OME will use all the available memory, before crashing without any error log.
**To Reproduce**
Just follow the guide from OME official guide:

- `docker run -d -p 1935:1935 -p 4000:4000/udp -p 3333:3333 -p 3334:3334 -p 3478:3478 -p 9000:9000 -p 9999:9999/udp airensoft/ovenmediaengine:0.14.15`
- Push an RTMP stream (with OBS in my case)

As you can see, I'm just using the defaul Server.xml config file

**Expected behavior**
I expect memory usage will be higher than IDLE condition. But after a (short?) while, memory usage should be stable.

**Logs**
As I stated, nothing was logged on error log when using the docker enviorment. I tried also with an Ubuntu 22 VM, and I found this error: 
`[OutboundWorker:141] ov.Queue | queue.h:268 | [0x560aa4596b70] LLHLS - Stream Data Queue size has exceeded the threshold: queue: 500, threshold: 500, peak: 500`
I can not say if the error happened just a moment before OME crashed because I was not looking at it and OME was started manually by me (instead of using systemd).

**Server 1:**
 - OS: Windows 10 with Docker desktop 4.14.1 and docker version 20.10.21, build baeda1f
 - OvenMediaEngine Version: v0.14.15
 - Branch: master

**Server 2:**
 - OS: Ubuntu 22.04 VM under Windows 10
 - OvenMediaEngine Version: v0.14.15 (manually compiled)
 - Branch: master
 
**Player (please complete the following information):**
I used the Oven Player with webrtc. But memory leak is happening also with 0 viewers.

**Additional context**
I tested both the server1 and server2 config in two different physical machines. Both of them with 32gb of RAM. One machine with Intel i7 8core cpu, the other with ryzen 9 5900x.
 OBS settings:
https://imgur.com/a/PYKJngD

About OBS settings: I also updated OBS to latest version and changed settings using settings proposed [here](https://github.com/AirenSoft/OvenMediaEngine/issues/921#issuecomment-1320957872) and [here](https://github.com/AirenSoft/OvenMediaEngine/issues/921#issuecomment-1320959064)

**Comment by getroot** [comment]
Please upload entire ovenmediaengine.log file.

**Comment by radar155** [comment]
https://gist.github.com/radar155/58c272b6351af339d86b94cfdb51a00f

I launched OME in docker (after launch 16mb of memory were used). I pushed with OBS an RTMP stream. After 3 minutes of streaming, RAM usage is 140mb and still growing.
I'm not going to close the stream to understand if a certain point it will be stable (as you suggested in #921 , now I'm using keyframe 2s instead of 0 on obs and investigating it

**Comment by getroot** [comment]
LLHLS stores chunks and segments in memory. And if the number of segments exceeds the set number, old segments are deleted. However, the memory libraries (glibc, jemalloc, etc.) do not immediately return the used memory to the OS when we delete a segment (holding memory reserved for a long time for performance).
It continues, and at some point the equilibrium strikes.
I'm also thinking about this these days, "Is this really the best?"

When keyframe is 0, LLHLS fails to create a segment in the worst case (since a segment must start with a keyframe) and continues to create chunks. So memory may increase. I'm thinking about how best to do this.

If you are not using LLHLS and only using WebRTC, remove it from Publishers settings. WebRTC uses very little memory.

**Comment by radar155** [comment]
Ok thank you, now it's clear.

About keyframe=0 and LLHLS: yes I think OME should be able to understand if it's failing when it tries to create a segment and in general it should be able to detect and handle memory leaks. If one or more user push data with wrong settings, the whole system memory usage is affected. Anyway, it looks you are already thinking how to handle all this :) .

**Comment by getroot** [comment]
@naanlizard 
When x264 keyframe=0 As you said, it is correct that a keyframe is created about once every 10 seconds, but depending on the video, there are cases where a keyframe does not occur for a very long time (more than 1 minute).

**Comment by radar155** [comment]
Ok I will check it soon

**Comment by getroot** [comment]
Since we enabled Jemalloc in 0.14.16 there will be a change in the memory usage you see on your system. Even checking with valgrind, there are no memory leaks found in stream creation/deletion. There will be memory that Jemalloc is holding on to without giving it back to the OS. This will be reused again or freed later.

**Comment by radar155** [comment]
Ok. Thank you for your effort. I will keep testing and if something occours I will let you know. Meanwhile maybe we could consider the issue as solved?
