### ISSUE TITLE
PPV Scenario - How to handle ?

### ISSUE THREAD

**Issue by KaiserSoz3** [AirenSoft/OvenMediaEngine#955]
Hello,
I hope you are well, I would like to congratulate you for the huge work you are doing, frankly I tried this week end several solutions: wowza, antmedia, red5 and I must say that despite the fact that these solutions are commercial, they are less good than your 100% open source solution that I find really well documented and simple to deploy with interesting features around WebRTC. 

I need a solution for a PPV platform with an interactive livestream (chat) hence the need to start on a solution based on Webrtc/LL Hls.

Scenario: A livestream is launched, several users are connected, then a viewer among them decides to start a private stream, all those who are connected are ejected from the stream except the one who starts the paying session, then some users have the possibility to join the private session, if the users who pay disconnect, the stream becomes public again.

On the client side it's easy to manage but solution on the server side is needed to prevent smart guys to access the stream.

How to manage this in your opinion?  I could pay if it requires additional development.

Thanks in advance

**Comment by kaizerdev** [comment]
I was thinking of a system based on token authentication that can be refreshed:
If a user A starts a private session we change the token of the stream, then he connectes to the stream with the new token (those already connected who have the old invalid token are disconnected), if a user B also wants to connect to the private session: we send a server side request to the OVE api to get the current token of the stream to connect.
if all these people who are in the paying session disconnect, we trigger an automatic event so that the token is automatically refreshed, and we send the new token to those who were in public to reconnect.

A feature like that would be very interesting and give your project a real edge over competitors.
It could even be a paid module

**Comment by getroot** [comment]
Thank you for giving OvenMediaEngine a great rating.

It is difficult to provide an application level API in OvenMediaEngine. However, OvenMediaEngine provides AdmissionWebhooks so that the server you develop can control access of broadcasters/viewers.

https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks

**Comment by kaizerdev** [comment]
Hello,
Yes I already checked that it but what if if I want to decline authorisation of users who are already connected to disconnect them.
Regarde

**Comment by IanMitchell77** [comment]
you could use AdmissionWebhooks by the sounds of this - see https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks

**Comment by kaizerdev** [comment]
yes but as my message above says how to kick people who already have an established connection (if we suddenly decide not to allow them)
@IanMitchell77 
@getroot

**Comment by getroot** [comment]
Currently there is no "kick" function. That feature is on our backlog, but it's not a high priority.

**Comment by kaizerdev** [comment]
Ok i understand so it will not be possible to built a secure PPV system using OVE :(
Possible to implement that feature if we sponsor the project ?

**Comment by getroot** [comment]
If what you said is a "kick feature" it will be implemented someday. I think I need this feature too.

Naturally, we watch requests from contributors (both financial and technical) more carefully, so the chances of that feature being boosted are very high.

However, please understand that it is not always guaranteed. For example, tasks that we believe will benefit more people will always be prioritized.

**Comment by kaizerdev** [comment]
Yes, but the solution I'm asking for goes beyond a simple "kick" feature that even I could implement myself.
It's the authorization system that needs to be redesigned, like invalidating authorizations and kicking instantly when you invalidate the authorization of someone who plays a stream.
It's a whole bunch of things.
I could have paid thousands of dollars not 50$, I'm going to turn to another solution more modular.
Thanks for your answers.

@getroot 
@IanMitchell77

**Comment by IanMitchell77** [comment]
AdmissionWebhooks lets you specify a lifetime in the response - I dont know what happens when that expires but presumably you have to ask for permission again. If the time this all took allowed playback to be smooth so when your not kicking people its fine then maybe the lifetime could be very small and you could reevaluate permission every second or so.

**Comment by kaizerdev** [comment]
Yes your idea is good but the problem is in the case where there is a site with high traffic, I do not see myself making a request per second per viewer to revalidate the authorization.

The solution is not optimal and could be improved to make PPV possible.
