### ISSUE TITLE
SIGSEGV on latest OME

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#956]
**Describe the bug**
Our OME instance (0.14.16) crashed with a SIGSEGV recently

Using docker, our dockerfile and server.xml

https://gist.github.com/naanlizard/152b7e22c7a9a043ce88ba8edd61b9bb

**Logs**
This log is only from a little before the crash. 
[omecrashred.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10100349/omecrashred.txt)

Here is the full log, it's quite large
[omecrashred2.txt.gz](https://github.com/AirenSoft/OvenMediaEngine/files/10100353/omecrashred2.txt.gz)

And the dump
[crash_20221128.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10100354/crash_20221128.dump.txt)

**Comment by naanlizard** [comment]
Hopefully it's not the jemalloc, I'd feel bad for the regression!

**Comment by getroot** [comment]
The crash dump file was not analyzed correctly due to a mismatch between airensoft/ovenmediaengine:0.14.16 and your binary. Your log is outputting OvenMediaEngine v0.14.15 (). Maybe cached binaries were used in the past?

The dump file wasn't perfect, but I took a hint from it and found the possibility of a crash (LLHLS stream deletion timing issue) that could occur with a very low probability in LLHLS and fixed it.

airensoft/ovenmediaengine:dev allows you to test if the issue is resolved.

If the problem persists, please re-upload the dump.

**Comment by naanlizard** [comment]
Ah apologies, it was technically the dev image from before the release. 

I will update and report back if there are more crashes

Hope the World Cup streams are going smoothly :)

**Comment by getroot** [comment]
Thank you! 
In fact, it has already been tested by applying it to a commercial service for more than a month, and it is still being serviced well without any problems. Of course, this is only one stream (one TV channel) and the stream is not deleted. And since this only works as LLHLS origin, it's very unlikely to actually be a problem. :-)

**Comment by naanlizard** [comment]
So far, no more crashes afaict, so I'll close this
