### ISSUE TITLE
is adaptive streaming supported and how do I configure the server?

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenMediaEngine#99]
How do I configure the server so that it supports adaptive streaming?

**Comment by getroot** [comment]
Right now for WebRTC's ABR, you need to create multiple streams and then switch them in the player. We are waiting for the best standard method for WebRTC ABR.

**Comment by IanMitchell77** [comment]
A few months back you said "I do not know the exact requirements of (Seamless stream switching). If you do not allow 1 Frame of flickering, it is very difficult. But general switching can be implemented naturally in the player."

To confirm, that is not possible now but might be soon - right?

**Comment by getroot** [comment]
Let's check clearly. We keep repeating the same story.

ABR Switching, which does not allow 1 frame flickering, is supported only at the protocol and browser level. Currently we only support ABR at the player level. Do you agree? The ABR method currently supported by OvenMediaEngine and OvenPlayer is to terminate the existing stream and play the new stream. Therefore, there must be some flicker.

The ABR supported at the WebRTC protocol level is https://www.w3.org/TR/webrtc-svc/ specification. And this is not yet a complete standard. We are waiting for this to be a complete standard. When the standard is complete, we will implement svc and simulcast to implement a complete ABR. But I am not sure that this will switch without 1 frame flickering. This is supported by the browser and I haven't seen this working yet.

And we cannot say that this will be implemented in OME soon. Because we have to wait for this to be a complete standard, then we need a lot of time to implement it.

I hope you have confirmed clearly.

**Comment by IanMitchell77** [comment]
So how do you configure the media engine and player for ABR? 1 frame of flicker is ok for now. When I switch streams it takes several seconds but maybe Im not switching optimally - how should I switch?

**Comment by getroot** [comment]
You are going back to the beginning of the discussion.
https://github.com/AirenSoft/OvenMediaEngine/issues/89#issuecomment-604943815

In my environment, your problem does not occur. What exactly do you mean by "Several seconds"? 3-4 seconds?

Is it the same if you test it at http://demo.ovenplayer.com? I can see the stream switching is done in less than 1 second with the same settings as you.

If you have the same problem at http://demo.ovenplayer.com, can you provide your webrtc streaming urls? I would like to analyze the stream.

**Comment by getroot** [comment]
Also, please refer to the following documents for OBS settings. Some information has been updated.

https://airensoft.gitbook.io/ovenmediaengine/getting-started

**Comment by IanMitchell77** [comment]
Can you can switch with 1 frame of flicker?

The note says "If you use the default configuration, and the RTMP publishing URL is rtmp://192.168.0.1:1935/app/stream, 
WebRTC URL will be 
ws://192.168.0.1:3333/app/stream_o
ws://192.168.0.1:3333/app/stream_webrtc"

If I have several streams, ws://?:3333/stream_1, ws://?:3333/stream_2 and ws://?:3333/stream_3 - how would I switch between them? What API? or should I us ws://?:3333/stream_webrtc as the URL?

**Comment by IanMitchell77** [comment]
Can you please tell me the URL's and options that you use with the test player?

**Comment by IanMitchell77** [comment]
My system isnt up right now...

**Comment by getroot** [comment]
naega wie jagseonghan geul-eul yusimhage dasi bwajusibsio. 
naneun 1cho miman-ui seuwiching-eul gyeongheomhaessdago malhaessseubnida. 1 frame of flickerga anibnida... naneun uliga deo isang 1 frame of flickere daehan yaegineun haji anh-ass-eumyeon johgessseubnida. nan dangsin-ege chungbunhi seolmyeonghaessdago saeng-gaghabnida. 

geuligo nae seoljeong-eun alae URLe issseubnida. igeos-eul dasi hanbeon yusimhi bwajusibsio. 
https://github.com/AirenSoft/OvenMediaEngine/issues/89#issuecomment-604943815

wie issneun nae seoljeong-e ttaleumyeon URLeun ws://host:port/app/stream_low_o, ws://host:port/app/stream_medium_o, ws://host:port/app/stream_high_o lo saengseongdoebnida.

munseoe issneun stream_owa stream_webrtcneun gibon seoljeong-eul sayonghaneun salamdeul-ege annaehaneun geos-ibnida. dangsin-eun imi Server.xmleul sujeonghamyeonseo sayonghago issgi ttaemun-e dangsin-ege haedangdoeneun naeyong-eun anibnida.

http://demo.ovenplayer.com-e jeobsoghaeseo dangsin-ui url( ws://?:3333/stream_1)eul neohgo add sourceleul keullig hasibsio. geuligo  ws://?:3333/stream_2leul neohgo hanbeon deo add sourceleul keullig hasibsio. geuligo  ws://?:3333/stream_3eul neohgo hanbeon deo add sourceleul keullig hasibsio. geuligo Load Player beoteun-eul keullighasibsio. geu hue peulleieo oleunjjog hadan-ui seoljeong beoteun-eul tonghae seo soseuleul byeongyeonghal su issseubnida. 

nan dangsin-i mueos-eul moleuneunji moleugessseubnida. 

siseutem-i dongjaghaji anh-eumyeon OvenMediaEngine.logleul na-ege boyeojueoyaman naega munjeleul bunseog hal su issseubnida. geuligo hangsang Dev Branchleul Pull hayeo choesin-ui seobeolo teseuteuleul jinhaenghaejusibsio. dangsin-i yejeon beojeon-eul sayonghandamyeon, naneun maeu keun honlan-eul neukkibnida.  

naneun dangsin-ege naui URLeul jegonghal su eobs-seubnida. nan dangsin-i sayonghal su issneun  Serverleul gajigo issji anhseubnida. naneun danji opeunsoseu peulojegteuleul jinhaenghago iss-eul ppun-ibnida.
자세히
1096/5000
Please take a look at the article I wrote above carefully.
I said I had less than 1 second of switching. It's not 1 frame of flicker ... I hope we don't talk about 1 frame of flicker anymore. I think I have explained enough to you.

And my settings are at the URL below. Please look at this again.
https://github.com/AirenSoft/OvenMediaEngine/issues/89#issuecomment-604943815

According to my settings above, the URL is generated as ws: // host: port / app / stream_low_o, ws: // host: port / app / stream_medium_o, ws: // host: port / app / stream_high_o.

The stream_o and stream_webrtc in the documentation are intended to guide people who use the default settings. This is not applicable to you because you are already using Server.xml while editing it.

Go to http://demo.ovenplayer.com, enter your url (ws: //?: 3333 / stream_1) and click add source. Then put ws: //?: 3333 / stream_2 and click add source once more. Then put ws: //?: 3333 / stream_3 and click add source once more. Then click the Load Player button. After that, you can change the source through the Settings button on the bottom right of the player.

I don't know what you don't know.

If the system doesn't work, you have to show me OvenMediaEngine.log so I can analyze the problem. And always pull the Dev Branch to test with the latest server. If you are using the old version, I am very confused.

I can't give you my url. I don't have a server you can use. I am just working on an open source project.

**Comment by getroot** [comment]
For the API of OvenPlayer used at http://demo.ovenplayer.com, please refer to the following document.

https://airensoft.gitbook.io/ovenplayer/

**Comment by getroot** [comment]
Since you said that stream switching takes a "SEVERAL SECONDS", I am trying to solve your problem. This is because my player completes switching in less than 1 second. Is this your problem? Right? And you want to reduce the switching time of several seconds to less "1 second", right? How many seconds does your player spend switching between streams? You just said Several seconds. Please tell me exactly how many seconds it takes. And tell me what your goals are.

**Comment by getroot** [comment]
I am suddenly confused. I thought you were talking about the previous problem again. Are you focused on switching the stream "automatically"?

If the network is very unstable during WebRTC playback and packet loss increases, the player will automatically attempt to switch sources. Source will try to play down from the first input Source in sequence. Are you saying this?

What confuses me is that you've said Switching takes several seconds over several times. Are you talking about a different topic from the one you created earlier? Please clarify the problem. Is it the time it takes to switch Source in Demo Player? Or is it time to automatically detect network condition?

If you're talking about automatic switching, you should have written this into the issue of OvenPlayer's repository.

As far as I know, OvenPlayer tries to play from the first source that comes in, and if the network is bad, it automatically tries to play the next source. I don't know any more than that.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
